-- =====================================================
-- INSERT KOTA/KABUPATEN LENGKAP INDONESIA
-- =====================================================
-- Script ini berisi semua kota dan kabupaten di Indonesia
-- dengan berbagai alias untuk keyword matching

-- Clear existing data
DELETE FROM kabupaten_kota_keywords;

-- Insert semua kota/kabupaten dengan 4 alias masing-masing
INSERT INTO kabupaten_kota_keywords (kabupaten_kota_name, keyword, is_alias) VALUES
    ('aceh barat', 'aceh barat', FALSE),
    ('aceh barat', 'kabupaten aceh barat', TRUE),
    ('aceh barat', 'kab aceh barat', TRUE),
    ('aceh barat', 'kota aceh barat', TRUE),
    ('aceh barat daya', 'aceh barat daya', FALSE),
    ('aceh barat daya', 'kabupaten aceh barat daya', TRUE),
    ('aceh barat daya', 'kab aceh barat daya', TRUE),
    ('aceh barat daya', 'kota aceh barat daya', TRUE),
    ('aceh besar', 'aceh besar', FALSE),
    ('aceh besar', 'kabupaten aceh besar', TRUE),
    ('aceh besar', 'kab aceh besar', TRUE),
    ('aceh besar', 'kota aceh besar', TRUE),
    ('aceh jaya', 'aceh jaya', FALSE),
    ('aceh jaya', 'kabupaten aceh jaya', TRUE),
    ('aceh jaya', 'kab aceh jaya', TRUE),
    ('aceh jaya', 'kota aceh jaya', TRUE),
    ('aceh selatan', 'aceh selatan', FALSE),
    ('aceh selatan', 'kabupaten aceh selatan', TRUE),
    ('aceh selatan', 'kab aceh selatan', TRUE),
    ('aceh selatan', 'kota aceh selatan', TRUE),
    ('aceh singkil', 'aceh singkil', FALSE),
    ('aceh singkil', 'kabupaten aceh singkil', TRUE),
    ('aceh singkil', 'kab aceh singkil', TRUE),
    ('aceh singkil', 'kota aceh singkil', TRUE),
    ('aceh tamiang', 'aceh tamiang', FALSE),
    ('aceh tamiang', 'kabupaten aceh tamiang', TRUE),
    ('aceh tamiang', 'kab aceh tamiang', TRUE),
    ('aceh tamiang', 'kota aceh tamiang', TRUE),
    ('aceh tengah', 'aceh tengah', FALSE),
    ('aceh tengah', 'kabupaten aceh tengah', TRUE),
    ('aceh tengah', 'kab aceh tengah', TRUE),
    ('aceh tengah', 'kota aceh tengah', TRUE),
    ('aceh tenggara', 'aceh tenggara', FALSE),
    ('aceh tenggara', 'kabupaten aceh tenggara', TRUE),
    ('aceh tenggara', 'kab aceh tenggara', TRUE),
    ('aceh tenggara', 'kota aceh tenggara', TRUE),
    ('aceh timur', 'aceh timur', FALSE),
    ('aceh timur', 'kabupaten aceh timur', TRUE),
    ('aceh timur', 'kab aceh timur', TRUE),
    ('aceh timur', 'kota aceh timur', TRUE),
    ('aceh utara', 'aceh utara', FALSE),
    ('aceh utara', 'kabupaten aceh utara', TRUE),
    ('aceh utara', 'kab aceh utara', TRUE),
    ('aceh utara', 'kota aceh utara', TRUE),
    ('banda aceh', 'banda aceh', FALSE),
    ('banda aceh', 'kabupaten banda aceh', TRUE),
    ('banda aceh', 'kab banda aceh', TRUE),
    ('banda aceh', 'kota banda aceh', TRUE),
    ('langsa', 'langsa', FALSE),
    ('langsa', 'kabupaten langsa', TRUE),
    ('langsa', 'kab langsa', TRUE),
    ('langsa', 'kota langsa', TRUE),
    ('lhokseumawe', 'lhokseumawe', FALSE),
    ('lhokseumawe', 'kabupaten lhokseumawe', TRUE),
    ('lhokseumawe', 'kab lhokseumawe', TRUE),
    ('lhokseumawe', 'kota lhokseumawe', TRUE),
    ('sabang', 'sabang', FALSE),
    ('sabang', 'kabupaten sabang', TRUE),
    ('sabang', 'kab sabang', TRUE),
    ('sabang', 'kota sabang', TRUE),
    ('subulussalam', 'subulussalam', FALSE),
    ('subulussalam', 'kabupaten subulussalam', TRUE),
    ('subulussalam', 'kab subulussalam', TRUE),
    ('subulussalam', 'kota subulussalam', TRUE),
    ('agam', 'agam', FALSE),
    ('agam', 'kabupaten agam', TRUE),
    ('agam', 'kab agam', TRUE),
    ('agam', 'kota agam', TRUE),
    ('asahan', 'asahan', FALSE),
    ('asahan', 'kabupaten asahan', TRUE),
    ('asahan', 'kab asahan', TRUE),
    ('asahan', 'kota asahan', TRUE),
    ('batubara', 'batubara', FALSE),
    ('batubara', 'kabupaten batubara', TRUE),
    ('batubara', 'kab batubara', TRUE),
    ('batubara', 'kota batubara', TRUE),
    ('dairi', 'dairi', FALSE),
    ('dairi', 'kabupaten dairi', TRUE),
    ('dairi', 'kab dairi', TRUE),
    ('dairi', 'kota dairi', TRUE),
    ('deli serdang', 'deli serdang', FALSE),
    ('deli serdang', 'kabupaten deli serdang', TRUE),
    ('deli serdang', 'kab deli serdang', TRUE),
    ('deli serdang', 'kota deli serdang', TRUE),
    ('humbang hasundutan', 'humbang hasundutan', FALSE),
    ('humbang hasundutan', 'kabupaten humbang hasundutan', TRUE),
    ('humbang hasundutan', 'kab humbang hasundutan', TRUE),
    ('humbang hasundutan', 'kota humbang hasundutan', TRUE),
    ('karo', 'karo', FALSE),
    ('karo', 'kabupaten karo', TRUE),
    ('karo', 'kab karo', TRUE),
    ('karo', 'kota karo', TRUE),
    ('labuhanbatu', 'labuhanbatu', FALSE),
    ('labuhanbatu', 'kabupaten labuhanbatu', TRUE),
    ('labuhanbatu', 'kab labuhanbatu', TRUE),
    ('labuhanbatu', 'kota labuhanbatu', TRUE),
    ('labuhanbatu selatan', 'labuhanbatu selatan', FALSE),
    ('labuhanbatu selatan', 'kabupaten labuhanbatu selatan', TRUE),
    ('labuhanbatu selatan', 'kab labuhanbatu selatan', TRUE),
    ('labuhanbatu selatan', 'kota labuhanbatu selatan', TRUE),
    ('labuhanbatu utara', 'labuhanbatu utara', FALSE),
    ('labuhanbatu utara', 'kabupaten labuhanbatu utara', TRUE),
    ('labuhanbatu utara', 'kab labuhanbatu utara', TRUE),
    ('labuhanbatu utara', 'kota labuhanbatu utara', TRUE),
    ('langkat', 'langkat', FALSE),
    ('langkat', 'kabupaten langkat', TRUE),
    ('langkat', 'kab langkat', TRUE),
    ('langkat', 'kota langkat', TRUE),
    ('mandailing natal', 'mandailing natal', FALSE),
    ('mandailing natal', 'kabupaten mandailing natal', TRUE),
    ('mandailing natal', 'kab mandailing natal', TRUE),
    ('mandailing natal', 'kota mandailing natal', TRUE),
    ('nias', 'nias', FALSE),
    ('nias', 'kabupaten nias', TRUE),
    ('nias', 'kab nias', TRUE),
    ('nias', 'kota nias', TRUE),
    ('nias barat', 'nias barat', FALSE),
    ('nias barat', 'kabupaten nias barat', TRUE),
    ('nias barat', 'kab nias barat', TRUE),
    ('nias barat', 'kota nias barat', TRUE),
    ('nias selatan', 'nias selatan', FALSE),
    ('nias selatan', 'kabupaten nias selatan', TRUE),
    ('nias selatan', 'kab nias selatan', TRUE),
    ('nias selatan', 'kota nias selatan', TRUE),
    ('nias utara', 'nias utara', FALSE),
    ('nias utara', 'kabupaten nias utara', TRUE),
    ('nias utara', 'kab nias utara', TRUE),
    ('nias utara', 'kota nias utara', TRUE),
    ('padang lawas', 'padang lawas', FALSE),
    ('padang lawas', 'kabupaten padang lawas', TRUE),
    ('padang lawas', 'kab padang lawas', TRUE),
    ('padang lawas', 'kota padang lawas', TRUE),
    ('padang lawas utara', 'padang lawas utara', FALSE),
    ('padang lawas utara', 'kabupaten padang lawas utara', TRUE),
    ('padang lawas utara', 'kab padang lawas utara', TRUE),
    ('padang lawas utara', 'kota padang lawas utara', TRUE),
    ('pakpak bharat', 'pakpak bharat', FALSE),
    ('pakpak bharat', 'kabupaten pakpak bharat', TRUE),
    ('pakpak bharat', 'kab pakpak bharat', TRUE),
    ('pakpak bharat', 'kota pakpak bharat', TRUE),
    ('samosir', 'samosir', FALSE),
    ('samosir', 'kabupaten samosir', TRUE),
    ('samosir', 'kab samosir', TRUE),
    ('samosir', 'kota samosir', TRUE),
    ('serdang bedagai', 'serdang bedagai', FALSE),
    ('serdang bedagai', 'kabupaten serdang bedagai', TRUE),
    ('serdang bedagai', 'kab serdang bedagai', TRUE),
    ('serdang bedagai', 'kota serdang bedagai', TRUE),
    ('simalungun', 'simalungun', FALSE),
    ('simalungun', 'kabupaten simalungun', TRUE),
    ('simalungun', 'kab simalungun', TRUE),
    ('simalungun', 'kota simalungun', TRUE),
    ('tapanuli selatan', 'tapanuli selatan', FALSE),
    ('tapanuli selatan', 'kabupaten tapanuli selatan', TRUE),
    ('tapanuli selatan', 'kab tapanuli selatan', TRUE),
    ('tapanuli selatan', 'kota tapanuli selatan', TRUE),
    ('tapanuli tengah', 'tapanuli tengah', FALSE),
    ('tapanuli tengah', 'kabupaten tapanuli tengah', TRUE),
    ('tapanuli tengah', 'kab tapanuli tengah', TRUE),
    ('tapanuli tengah', 'kota tapanuli tengah', TRUE),
    ('tapanuli utara', 'tapanuli utara', FALSE),
    ('tapanuli utara', 'kabupaten tapanuli utara', TRUE),
    ('tapanuli utara', 'kab tapanuli utara', TRUE),
    ('tapanuli utara', 'kota tapanuli utara', TRUE),
    ('toba', 'toba', FALSE),
    ('toba', 'kabupaten toba', TRUE),
    ('toba', 'kab toba', TRUE),
    ('toba', 'kota toba', TRUE),
    ('toba samosir', 'toba samosir', FALSE),
    ('toba samosir', 'kabupaten toba samosir', TRUE),
    ('toba samosir', 'kab toba samosir', TRUE),
    ('toba samosir', 'kota toba samosir', TRUE),
    ('binjai', 'binjai', FALSE),
    ('binjai', 'kabupaten binjai', TRUE),
    ('binjai', 'kab binjai', TRUE),
    ('binjai', 'kota binjai', TRUE),
    ('gunungsitoli', 'gunungsitoli', FALSE),
    ('gunungsitoli', 'kabupaten gunungsitoli', TRUE),
    ('gunungsitoli', 'kab gunungsitoli', TRUE),
    ('gunungsitoli', 'kota gunungsitoli', TRUE),
    ('medan', 'medan', FALSE),
    ('medan', 'kabupaten medan', TRUE),
    ('medan', 'kab medan', TRUE),
    ('medan', 'kota medan', TRUE),
    ('padang sidempuan', 'padang sidempuan', FALSE),
    ('padang sidempuan', 'kabupaten padang sidempuan', TRUE),
    ('padang sidempuan', 'kab padang sidempuan', TRUE),
    ('padang sidempuan', 'kota padang sidempuan', TRUE),
    ('pematang siantar', 'pematang siantar', FALSE),
    ('pematang siantar', 'kabupaten pematang siantar', TRUE),
    ('pematang siantar', 'kab pematang siantar', TRUE),
    ('pematang siantar', 'kota pematang siantar', TRUE),
    ('sibolga', 'sibolga', FALSE),
    ('sibolga', 'kabupaten sibolga', TRUE),
    ('sibolga', 'kab sibolga', TRUE),
    ('sibolga', 'kota sibolga', TRUE),
    ('tanjung balai', 'tanjung balai', FALSE),
    ('tanjung balai', 'kabupaten tanjung balai', TRUE),
    ('tanjung balai', 'kab tanjung balai', TRUE),
    ('tanjung balai', 'kota tanjung balai', TRUE),
    ('tebing tinggi', 'tebing tinggi', FALSE),
    ('tebing tinggi', 'kabupaten tebing tinggi', TRUE),
    ('tebing tinggi', 'kab tebing tinggi', TRUE),
    ('tebing tinggi', 'kota tebing tinggi', TRUE),
    ('dharmasraya', 'dharmasraya', FALSE),
    ('dharmasraya', 'kabupaten dharmasraya', TRUE),
    ('dharmasraya', 'kab dharmasraya', TRUE),
    ('dharmasraya', 'kota dharmasraya', TRUE),
    ('kepulauan mentawai', 'kepulauan mentawai', FALSE),
    ('kepulauan mentawai', 'kabupaten kepulauan mentawai', TRUE),
    ('kepulauan mentawai', 'kab kepulauan mentawai', TRUE),
    ('kepulauan mentawai', 'kota kepulauan mentawai', TRUE),
    ('lima puluh kota', 'lima puluh kota', FALSE),
    ('lima puluh kota', 'kabupaten lima puluh kota', TRUE),
    ('lima puluh kota', 'kab lima puluh kota', TRUE),
    ('lima puluh kota', 'kota lima puluh kota', TRUE),
    ('padang pariaman', 'padang pariaman', FALSE),
    ('padang pariaman', 'kabupaten padang pariaman', TRUE),
    ('padang pariaman', 'kab padang pariaman', TRUE),
    ('padang pariaman', 'kota padang pariaman', TRUE),
    ('pasaman', 'pasaman', FALSE),
    ('pasaman', 'kabupaten pasaman', TRUE),
    ('pasaman', 'kab pasaman', TRUE),
    ('pasaman', 'kota pasaman', TRUE),
    ('pasaman barat', 'pasaman barat', FALSE),
    ('pasaman barat', 'kabupaten pasaman barat', TRUE),
    ('pasaman barat', 'kab pasaman barat', TRUE),
    ('pasaman barat', 'kota pasaman barat', TRUE),
    ('pesisir selatan', 'pesisir selatan', FALSE),
    ('pesisir selatan', 'kabupaten pesisir selatan', TRUE),
    ('pesisir selatan', 'kab pesisir selatan', TRUE),
    ('pesisir selatan', 'kota pesisir selatan', TRUE),
    ('sijunjung', 'sijunjung', FALSE),
    ('sijunjung', 'kabupaten sijunjung', TRUE),
    ('sijunjung', 'kab sijunjung', TRUE),
    ('sijunjung', 'kota sijunjung', TRUE),
    ('solok', 'solok', FALSE),
    ('solok', 'kabupaten solok', TRUE),
    ('solok', 'kab solok', TRUE),
    ('solok', 'kota solok', TRUE),
    ('solok selatan', 'solok selatan', FALSE),
    ('solok selatan', 'kabupaten solok selatan', TRUE),
    ('solok selatan', 'kab solok selatan', TRUE),
    ('solok selatan', 'kota solok selatan', TRUE),
    ('tanah datar', 'tanah datar', FALSE),
    ('tanah datar', 'kabupaten tanah datar', TRUE),
    ('tanah datar', 'kab tanah datar', TRUE),
    ('tanah datar', 'kota tanah datar', TRUE),
    ('bukittinggi', 'bukittinggi', FALSE),
    ('bukittinggi', 'kabupaten bukittinggi', TRUE),
    ('bukittinggi', 'kab bukittinggi', TRUE),
    ('bukittinggi', 'kota bukittinggi', TRUE),
    ('padang', 'padang', FALSE),
    ('padang', 'kabupaten padang', TRUE),
    ('padang', 'kab padang', TRUE),
    ('padang', 'kota padang', TRUE),
    ('padang panjang', 'padang panjang', FALSE),
    ('padang panjang', 'kabupaten padang panjang', TRUE),
    ('padang panjang', 'kab padang panjang', TRUE),
    ('padang panjang', 'kota padang panjang', TRUE),
    ('pariaman', 'pariaman', FALSE),
    ('pariaman', 'kabupaten pariaman', TRUE),
    ('pariaman', 'kab pariaman', TRUE),
    ('pariaman', 'kota pariaman', TRUE),
    ('payakumbuh', 'payakumbuh', FALSE),
    ('payakumbuh', 'kabupaten payakumbuh', TRUE),
    ('payakumbuh', 'kab payakumbuh', TRUE),
    ('payakumbuh', 'kota payakumbuh', TRUE),
    ('sawah lunto', 'sawah lunto', FALSE),
    ('sawah lunto', 'kabupaten sawah lunto', TRUE),
    ('sawah lunto', 'kab sawah lunto', TRUE),
    ('sawah lunto', 'kota sawah lunto', TRUE),
    ('bengkalis', 'bengkalis', FALSE),
    ('bengkalis', 'kabupaten bengkalis', TRUE),
    ('bengkalis', 'kab bengkalis', TRUE),
    ('bengkalis', 'kota bengkalis', TRUE),
    ('indragiri hilir', 'indragiri hilir', FALSE),
    ('indragiri hilir', 'kabupaten indragiri hilir', TRUE),
    ('indragiri hilir', 'kab indragiri hilir', TRUE),
    ('indragiri hilir', 'kota indragiri hilir', TRUE),
    ('indragiri hulu', 'indragiri hulu', FALSE),
    ('indragiri hulu', 'kabupaten indragiri hulu', TRUE),
    ('indragiri hulu', 'kab indragiri hulu', TRUE),
    ('indragiri hulu', 'kota indragiri hulu', TRUE),
    ('kampar', 'kampar', FALSE),
    ('kampar', 'kabupaten kampar', TRUE),
    ('kampar', 'kab kampar', TRUE),
    ('kampar', 'kota kampar', TRUE),
    ('kepulauan anambas', 'kepulauan anambas', FALSE),
    ('kepulauan anambas', 'kabupaten kepulauan anambas', TRUE),
    ('kepulauan anambas', 'kab kepulauan anambas', TRUE),
    ('kepulauan anambas', 'kota kepulauan anambas', TRUE),
    ('kepulauan meranti', 'kepulauan meranti', FALSE),
    ('kepulauan meranti', 'kabupaten kepulauan meranti', TRUE),
    ('kepulauan meranti', 'kab kepulauan meranti', TRUE),
    ('kepulauan meranti', 'kota kepulauan meranti', TRUE),
    ('kuantan singingi', 'kuantan singingi', FALSE),
    ('kuantan singingi', 'kabupaten kuantan singingi', TRUE),
    ('kuantan singingi', 'kab kuantan singingi', TRUE),
    ('kuantan singingi', 'kota kuantan singingi', TRUE),
    ('pelalawan', 'pelalawan', FALSE),
    ('pelalawan', 'kabupaten pelalawan', TRUE),
    ('pelalawan', 'kab pelalawan', TRUE),
    ('pelalawan', 'kota pelalawan', TRUE),
    ('rokan hilir', 'rokan hilir', FALSE),
    ('rokan hilir', 'kabupaten rokan hilir', TRUE),
    ('rokan hilir', 'kab rokan hilir', TRUE),
    ('rokan hilir', 'kota rokan hilir', TRUE),
    ('rokan hulu', 'rokan hulu', FALSE),
    ('rokan hulu', 'kabupaten rokan hulu', TRUE),
    ('rokan hulu', 'kab rokan hulu', TRUE),
    ('rokan hulu', 'kota rokan hulu', TRUE),
    ('siak', 'siak', FALSE),
    ('siak', 'kabupaten siak', TRUE),
    ('siak', 'kab siak', TRUE),
    ('siak', 'kota siak', TRUE),
    ('dumai', 'dumai', FALSE),
    ('dumai', 'kabupaten dumai', TRUE),
    ('dumai', 'kab dumai', TRUE),
    ('dumai', 'kota dumai', TRUE),
    ('pekanbaru', 'pekanbaru', FALSE),
    ('pekanbaru', 'kabupaten pekanbaru', TRUE),
    ('pekanbaru', 'kab pekanbaru', TRUE),
    ('pekanbaru', 'kota pekanbaru', TRUE),
    ('bintan', 'bintan', FALSE),
    ('bintan', 'kabupaten bintan', TRUE),
    ('bintan', 'kab bintan', TRUE),
    ('bintan', 'kota bintan', TRUE),
    ('karimun', 'karimun', FALSE),
    ('karimun', 'kabupaten karimun', TRUE),
    ('karimun', 'kab karimun', TRUE),
    ('karimun', 'kota karimun', TRUE),
    ('lingga', 'lingga', FALSE),
    ('lingga', 'kabupaten lingga', TRUE),
    ('lingga', 'kab lingga', TRUE),
    ('lingga', 'kota lingga', TRUE),
    ('natuna', 'natuna', FALSE),
    ('natuna', 'kabupaten natuna', TRUE),
    ('natuna', 'kab natuna', TRUE),
    ('natuna', 'kota natuna', TRUE),
    ('batam', 'batam', FALSE),
    ('batam', 'kabupaten batam', TRUE),
    ('batam', 'kab batam', TRUE),
    ('batam', 'kota batam', TRUE),
    ('tanjung pinang', 'tanjung pinang', FALSE),
    ('tanjung pinang', 'kabupaten tanjung pinang', TRUE),
    ('tanjung pinang', 'kab tanjung pinang', TRUE),
    ('tanjung pinang', 'kota tanjung pinang', TRUE),
    ('bungo', 'bungo', FALSE),
    ('bungo', 'kabupaten bungo', TRUE),
    ('bungo', 'kab bungo', TRUE),
    ('bungo', 'kota bungo', TRUE),
    ('kerinci', 'kerinci', FALSE),
    ('kerinci', 'kabupaten kerinci', TRUE),
    ('kerinci', 'kab kerinci', TRUE),
    ('kerinci', 'kota kerinci', TRUE),
    ('merangin', 'merangin', FALSE),
    ('merangin', 'kabupaten merangin', TRUE),
    ('merangin', 'kab merangin', TRUE),
    ('merangin', 'kota merangin', TRUE),
    ('muaro jambi', 'muaro jambi', FALSE),
    ('muaro jambi', 'kabupaten muaro jambi', TRUE),
    ('muaro jambi', 'kab muaro jambi', TRUE),
    ('muaro jambi', 'kota muaro jambi', TRUE),
    ('sarolangun', 'sarolangun', FALSE),
    ('sarolangun', 'kabupaten sarolangun', TRUE),
    ('sarolangun', 'kab sarolangun', TRUE),
    ('sarolangun', 'kota sarolangun', TRUE),
    ('tanjung jabung barat', 'tanjung jabung barat', FALSE),
    ('tanjung jabung barat', 'kabupaten tanjung jabung barat', TRUE),
    ('tanjung jabung barat', 'kab tanjung jabung barat', TRUE),
    ('tanjung jabung barat', 'kota tanjung jabung barat', TRUE),
    ('tanjung jabung timur', 'tanjung jabung timur', FALSE),
    ('tanjung jabung timur', 'kabupaten tanjung jabung timur', TRUE),
    ('tanjung jabung timur', 'kab tanjung jabung timur', TRUE),
    ('tanjung jabung timur', 'kota tanjung jabung timur', TRUE),
    ('tebo', 'tebo', FALSE),
    ('tebo', 'kabupaten tebo', TRUE),
    ('tebo', 'kab tebo', TRUE),
    ('tebo', 'kota tebo', TRUE),
    ('jambi', 'jambi', FALSE),
    ('jambi', 'kabupaten jambi', TRUE),
    ('jambi', 'kab jambi', TRUE),
    ('jambi', 'kota jambi', TRUE),
    ('sungaipenuh', 'sungaipenuh', FALSE),
    ('sungaipenuh', 'kabupaten sungaipenuh', TRUE),
    ('sungaipenuh', 'kab sungaipenuh', TRUE),
    ('sungaipenuh', 'kota sungaipenuh', TRUE),
    ('banyuasin', 'banyuasin', FALSE),
    ('banyuasin', 'kabupaten banyuasin', TRUE),
    ('banyuasin', 'kab banyuasin', TRUE),
    ('banyuasin', 'kota banyuasin', TRUE),
    ('empat lawang', 'empat lawang', FALSE),
    ('empat lawang', 'kabupaten empat lawang', TRUE),
    ('empat lawang', 'kab empat lawang', TRUE),
    ('empat lawang', 'kota empat lawang', TRUE),
    ('lahat', 'lahat', FALSE),
    ('lahat', 'kabupaten lahat', TRUE),
    ('lahat', 'kab lahat', TRUE),
    ('lahat', 'kota lahat', TRUE),
    ('muara enim', 'muara enim', FALSE),
    ('muara enim', 'kabupaten muara enim', TRUE),
    ('muara enim', 'kab muara enim', TRUE),
    ('muara enim', 'kota muara enim', TRUE),
    ('musi banyuasin', 'musi banyuasin', FALSE),
    ('musi banyuasin', 'kabupaten musi banyuasin', TRUE),
    ('musi banyuasin', 'kab musi banyuasin', TRUE),
    ('musi banyuasin', 'kota musi banyuasin', TRUE),
    ('musi rawas', 'musi rawas', FALSE),
    ('musi rawas', 'kabupaten musi rawas', TRUE),
    ('musi rawas', 'kab musi rawas', TRUE),
    ('musi rawas', 'kota musi rawas', TRUE),
    ('musi rawas utara', 'musi rawas utara', FALSE),
    ('musi rawas utara', 'kabupaten musi rawas utara', TRUE),
    ('musi rawas utara', 'kab musi rawas utara', TRUE),
    ('musi rawas utara', 'kota musi rawas utara', TRUE),
    ('ogan ilir', 'ogan ilir', FALSE),
    ('ogan ilir', 'kabupaten ogan ilir', TRUE),
    ('ogan ilir', 'kab ogan ilir', TRUE),
    ('ogan ilir', 'kota ogan ilir', TRUE),
    ('ogan komering ilir', 'ogan komering ilir', FALSE),
    ('ogan komering ilir', 'kabupaten ogan komering ilir', TRUE),
    ('ogan komering ilir', 'kab ogan komering ilir', TRUE),
    ('ogan komering ilir', 'kota ogan komering ilir', TRUE),
    ('ogan komering ulu', 'ogan komering ulu', FALSE),
    ('ogan komering ulu', 'kabupaten ogan komering ulu', TRUE),
    ('ogan komering ulu', 'kab ogan komering ulu', TRUE),
    ('ogan komering ulu', 'kota ogan komering ulu', TRUE),
    ('ogan komering ulu selatan', 'ogan komering ulu selatan', FALSE),
    ('ogan komering ulu selatan', 'kabupaten ogan komering ulu selatan', TRUE),
    ('ogan komering ulu selatan', 'kab ogan komering ulu selatan', TRUE),
    ('ogan komering ulu selatan', 'kota ogan komering ulu selatan', TRUE),
    ('ogan komering ulu timur', 'ogan komering ulu timur', FALSE),
    ('ogan komering ulu timur', 'kabupaten ogan komering ulu timur', TRUE),
    ('ogan komering ulu timur', 'kab ogan komering ulu timur', TRUE),
    ('ogan komering ulu timur', 'kota ogan komering ulu timur', TRUE),
    ('penukal abab lematang ilir', 'penukal abab lematang ilir', FALSE),
    ('penukal abab lematang ilir', 'kabupaten penukal abab lematang ilir', TRUE),
    ('penukal abab lematang ilir', 'kab penukal abab lematang ilir', TRUE),
    ('penukal abab lematang ilir', 'kota penukal abab lematang ilir', TRUE),
    ('palembang', 'palembang', FALSE),
    ('palembang', 'kabupaten palembang', TRUE),
    ('palembang', 'kab palembang', TRUE),
    ('palembang', 'kota palembang', TRUE),
    ('prabumulih', 'prabumulih', FALSE),
    ('prabumulih', 'kabupaten prabumulih', TRUE),
    ('prabumulih', 'kab prabumulih', TRUE),
    ('prabumulih', 'kota prabumulih', TRUE),
    ('bengkulu', 'bengkulu', FALSE),
    ('bengkulu', 'kabupaten bengkulu', TRUE),
    ('bengkulu', 'kab bengkulu', TRUE),
    ('bengkulu', 'kota bengkulu', TRUE),
    ('bengkulu selatan', 'bengkulu selatan', FALSE),
    ('bengkulu selatan', 'kabupaten bengkulu selatan', TRUE),
    ('bengkulu selatan', 'kab bengkulu selatan', TRUE),
    ('bengkulu selatan', 'kota bengkulu selatan', TRUE),
    ('bengkulu tengah', 'bengkulu tengah', FALSE),
    ('bengkulu tengah', 'kabupaten bengkulu tengah', TRUE),
    ('bengkulu tengah', 'kab bengkulu tengah', TRUE),
    ('bengkulu tengah', 'kota bengkulu tengah', TRUE),
    ('bengkulu utara', 'bengkulu utara', FALSE),
    ('bengkulu utara', 'kabupaten bengkulu utara', TRUE),
    ('bengkulu utara', 'kab bengkulu utara', TRUE),
    ('bengkulu utara', 'kota bengkulu utara', TRUE),
    ('kaur', 'kaur', FALSE),
    ('kaur', 'kabupaten kaur', TRUE),
    ('kaur', 'kab kaur', TRUE),
    ('kaur', 'kota kaur', TRUE),
    ('kepahiang', 'kepahiang', FALSE),
    ('kepahiang', 'kabupaten kepahiang', TRUE),
    ('kepahiang', 'kab kepahiang', TRUE),
    ('kepahiang', 'kota kepahiang', TRUE),
    ('lebong', 'lebong', FALSE),
    ('lebong', 'kabupaten lebong', TRUE),
    ('lebong', 'kab lebong', TRUE),
    ('lebong', 'kota lebong', TRUE),
    ('muko muko', 'muko muko', FALSE),
    ('muko muko', 'kabupaten muko muko', TRUE),
    ('muko muko', 'kab muko muko', TRUE),
    ('muko muko', 'kota muko muko', TRUE),
    ('rejang lebong', 'rejang lebong', FALSE),
    ('rejang lebong', 'kabupaten rejang lebong', TRUE),
    ('rejang lebong', 'kab rejang lebong', TRUE),
    ('rejang lebong', 'kota rejang lebong', TRUE),
    ('seluma', 'seluma', FALSE),
    ('seluma', 'kabupaten seluma', TRUE),
    ('seluma', 'kab seluma', TRUE),
    ('seluma', 'kota seluma', TRUE),
    ('lampung barat', 'lampung barat', FALSE),
    ('lampung barat', 'kabupaten lampung barat', TRUE),
    ('lampung barat', 'kab lampung barat', TRUE),
    ('lampung barat', 'kota lampung barat', TRUE),
    ('lampung selatan', 'lampung selatan', FALSE),
    ('lampung selatan', 'kabupaten lampung selatan', TRUE),
    ('lampung selatan', 'kab lampung selatan', TRUE),
    ('lampung selatan', 'kota lampung selatan', TRUE),
    ('lampung tengah', 'lampung tengah', FALSE),
    ('lampung tengah', 'kabupaten lampung tengah', TRUE),
    ('lampung tengah', 'kab lampung tengah', TRUE),
    ('lampung tengah', 'kota lampung tengah', TRUE),
    ('lampung timur', 'lampung timur', FALSE),
    ('lampung timur', 'kabupaten lampung timur', TRUE),
    ('lampung timur', 'kab lampung timur', TRUE),
    ('lampung timur', 'kota lampung timur', TRUE),
    ('lampung utara', 'lampung utara', FALSE),
    ('lampung utara', 'kabupaten lampung utara', TRUE),
    ('lampung utara', 'kab lampung utara', TRUE),
    ('lampung utara', 'kota lampung utara', TRUE),
    ('mesuji', 'mesuji', FALSE),
    ('mesuji', 'kabupaten mesuji', TRUE),
    ('mesuji', 'kab mesuji', TRUE),
    ('mesuji', 'kota mesuji', TRUE),
    ('pesawaran', 'pesawaran', FALSE),
    ('pesawaran', 'kabupaten pesawaran', TRUE),
    ('pesawaran', 'kab pesawaran', TRUE),
    ('pesawaran', 'kota pesawaran', TRUE),
    ('pesisir barat', 'pesisir barat', FALSE),
    ('pesisir barat', 'kabupaten pesisir barat', TRUE),
    ('pesisir barat', 'kab pesisir barat', TRUE),
    ('pesisir barat', 'kota pesisir barat', TRUE),
    ('pringsewu', 'pringsewu', FALSE),
    ('pringsewu', 'kabupaten pringsewu', TRUE),
    ('pringsewu', 'kab pringsewu', TRUE),
    ('pringsewu', 'kota pringsewu', TRUE),
    ('tulang bawang', 'tulang bawang', FALSE),
    ('tulang bawang', 'kabupaten tulang bawang', TRUE),
    ('tulang bawang', 'kab tulang bawang', TRUE),
    ('tulang bawang', 'kota tulang bawang', TRUE),
    ('tulang bawang barat', 'tulang bawang barat', FALSE),
    ('tulang bawang barat', 'kabupaten tulang bawang barat', TRUE),
    ('tulang bawang barat', 'kab tulang bawang barat', TRUE),
    ('tulang bawang barat', 'kota tulang bawang barat', TRUE),
    ('way kanan', 'way kanan', FALSE),
    ('way kanan', 'kabupaten way kanan', TRUE),
    ('way kanan', 'kab way kanan', TRUE),
    ('way kanan', 'kota way kanan', TRUE),
    ('bandar lampung', 'bandar lampung', FALSE),
    ('bandar lampung', 'kabupaten bandar lampung', TRUE),
    ('bandar lampung', 'kab bandar lampung', TRUE),
    ('bandar lampung', 'kota bandar lampung', TRUE),
    ('metro', 'metro', FALSE),
    ('metro', 'kabupaten metro', TRUE),
    ('metro', 'kab metro', TRUE),
    ('metro', 'kota metro', TRUE),
    ('bangka', 'bangka', FALSE),
    ('bangka', 'kabupaten bangka', TRUE),
    ('bangka', 'kab bangka', TRUE),
    ('bangka', 'kota bangka', TRUE),
    ('bangka barat', 'bangka barat', FALSE),
    ('bangka barat', 'kabupaten bangka barat', TRUE),
    ('bangka barat', 'kab bangka barat', TRUE),
    ('bangka barat', 'kota bangka barat', TRUE),
    ('bangka selatan', 'bangka selatan', FALSE),
    ('bangka selatan', 'kabupaten bangka selatan', TRUE),
    ('bangka selatan', 'kab bangka selatan', TRUE),
    ('bangka selatan', 'kota bangka selatan', TRUE),
    ('bangka tengah', 'bangka tengah', FALSE),
    ('bangka tengah', 'kabupaten bangka tengah', TRUE),
    ('bangka tengah', 'kab bangka tengah', TRUE),
    ('bangka tengah', 'kota bangka tengah', TRUE),
    ('belitung', 'belitung', FALSE),
    ('belitung', 'kabupaten belitung', TRUE),
    ('belitung', 'kab belitung', TRUE),
    ('belitung', 'kota belitung', TRUE),
    ('belitung timur', 'belitung timur', FALSE),
    ('belitung timur', 'kabupaten belitung timur', TRUE),
    ('belitung timur', 'kab belitung timur', TRUE),
    ('belitung timur', 'kota belitung timur', TRUE),
    ('pangkal pinang', 'pangkal pinang', FALSE),
    ('pangkal pinang', 'kabupaten pangkal pinang', TRUE),
    ('pangkal pinang', 'kab pangkal pinang', TRUE),
    ('pangkal pinang', 'kota pangkal pinang', TRUE),
    ('jakarta barat', 'jakarta barat', FALSE),
    ('jakarta barat', 'kabupaten jakarta barat', TRUE),
    ('jakarta barat', 'kab jakarta barat', TRUE),
    ('jakarta barat', 'kota jakarta barat', TRUE),
    ('jakarta pusat', 'jakarta pusat', FALSE),
    ('jakarta pusat', 'kabupaten jakarta pusat', TRUE),
    ('jakarta pusat', 'kab jakarta pusat', TRUE),
    ('jakarta pusat', 'kota jakarta pusat', TRUE),
    ('jakarta selatan', 'jakarta selatan', FALSE),
    ('jakarta selatan', 'kabupaten jakarta selatan', TRUE),
    ('jakarta selatan', 'kab jakarta selatan', TRUE),
    ('jakarta selatan', 'kota jakarta selatan', TRUE),
    ('jakarta timur', 'jakarta timur', FALSE),
    ('jakarta timur', 'kabupaten jakarta timur', TRUE),
    ('jakarta timur', 'kab jakarta timur', TRUE),
    ('jakarta timur', 'kota jakarta timur', TRUE),
    ('jakarta utara', 'jakarta utara', FALSE),
    ('jakarta utara', 'kabupaten jakarta utara', TRUE),
    ('jakarta utara', 'kab jakarta utara', TRUE),
    ('jakarta utara', 'kota jakarta utara', TRUE),
    ('kepulauan seribu', 'kepulauan seribu', FALSE),
    ('kepulauan seribu', 'kabupaten kepulauan seribu', TRUE),
    ('kepulauan seribu', 'kab kepulauan seribu', TRUE),
    ('kepulauan seribu', 'kota kepulauan seribu', TRUE),
    ('bandung', 'bandung', FALSE),
    ('bandung', 'kabupaten bandung', TRUE),
    ('bandung', 'kab bandung', TRUE),
    ('bandung', 'kota bandung', TRUE),
    ('bandung barat', 'bandung barat', FALSE),
    ('bandung barat', 'kabupaten bandung barat', TRUE),
    ('bandung barat', 'kab bandung barat', TRUE),
    ('bandung barat', 'kota bandung barat', TRUE),
    ('bekasi', 'bekasi', FALSE),
    ('bekasi', 'kabupaten bekasi', TRUE),
    ('bekasi', 'kab bekasi', TRUE),
    ('bekasi', 'kota bekasi', TRUE),
    ('bogor', 'bogor', FALSE),
    ('bogor', 'kabupaten bogor', TRUE),
    ('bogor', 'kab bogor', TRUE),
    ('bogor', 'kota bogor', TRUE),
    ('ciamis', 'ciamis', FALSE),
    ('ciamis', 'kabupaten ciamis', TRUE),
    ('ciamis', 'kab ciamis', TRUE),
    ('ciamis', 'kota ciamis', TRUE),
    ('cianjur', 'cianjur', FALSE),
    ('cianjur', 'kabupaten cianjur', TRUE),
    ('cianjur', 'kab cianjur', TRUE),
    ('cianjur', 'kota cianjur', TRUE),
    ('cilacap', 'cilacap', FALSE),
    ('cilacap', 'kabupaten cilacap', TRUE),
    ('cilacap', 'kab cilacap', TRUE),
    ('cilacap', 'kota cilacap', TRUE),
    ('cirebon', 'cirebon', FALSE),
    ('cirebon', 'kabupaten cirebon', TRUE),
    ('cirebon', 'kab cirebon', TRUE),
    ('cirebon', 'kota cirebon', TRUE),
    ('garut', 'garut', FALSE),
    ('garut', 'kabupaten garut', TRUE),
    ('garut', 'kab garut', TRUE),
    ('garut', 'kota garut', TRUE),
    ('indramayu', 'indramayu', FALSE),
    ('indramayu', 'kabupaten indramayu', TRUE),
    ('indramayu', 'kab indramayu', TRUE),
    ('indramayu', 'kota indramayu', TRUE),
    ('karawang', 'karawang', FALSE),
    ('karawang', 'kabupaten karawang', TRUE),
    ('karawang', 'kab karawang', TRUE),
    ('karawang', 'kota karawang', TRUE),
    ('kuningan', 'kuningan', FALSE),
    ('kuningan', 'kabupaten kuningan', TRUE),
    ('kuningan', 'kab kuningan', TRUE),
    ('kuningan', 'kota kuningan', TRUE),
    ('majalengka', 'majalengka', FALSE),
    ('majalengka', 'kabupaten majalengka', TRUE),
    ('majalengka', 'kab majalengka', TRUE),
    ('majalengka', 'kota majalengka', TRUE),
    ('pangandaran', 'pangandaran', FALSE),
    ('pangandaran', 'kabupaten pangandaran', TRUE),
    ('pangandaran', 'kab pangandaran', TRUE),
    ('pangandaran', 'kota pangandaran', TRUE),
    ('purwakarta', 'purwakarta', FALSE),
    ('purwakarta', 'kabupaten purwakarta', TRUE),
    ('purwakarta', 'kab purwakarta', TRUE),
    ('purwakarta', 'kota purwakarta', TRUE),
    ('subang', 'subang', FALSE),
    ('subang', 'kabupaten subang', TRUE),
    ('subang', 'kab subang', TRUE),
    ('subang', 'kota subang', TRUE),
    ('sukabumi', 'sukabumi', FALSE),
    ('sukabumi', 'kabupaten sukabumi', TRUE),
    ('sukabumi', 'kab sukabumi', TRUE),
    ('sukabumi', 'kota sukabumi', TRUE),
    ('sumedang', 'sumedang', FALSE),
    ('sumedang', 'kabupaten sumedang', TRUE),
    ('sumedang', 'kab sumedang', TRUE),
    ('sumedang', 'kota sumedang', TRUE),
    ('tasikmalaya', 'tasikmalaya', FALSE),
    ('tasikmalaya', 'kabupaten tasikmalaya', TRUE),
    ('tasikmalaya', 'kab tasikmalaya', TRUE),
    ('tasikmalaya', 'kota tasikmalaya', TRUE),
    ('banjar', 'banjar', FALSE),
    ('banjar', 'kabupaten banjar', TRUE),
    ('banjar', 'kab banjar', TRUE),
    ('banjar', 'kota banjar', TRUE),
    ('cimahi', 'cimahi', FALSE),
    ('cimahi', 'kabupaten cimahi', TRUE),
    ('cimahi', 'kab cimahi', TRUE),
    ('cimahi', 'kota cimahi', TRUE),
    ('depok', 'depok', FALSE),
    ('depok', 'kabupaten depok', TRUE),
    ('depok', 'kab depok', TRUE),
    ('depok', 'kota depok', TRUE),
    ('banjarnegara', 'banjarnegara', FALSE),
    ('banjarnegara', 'kabupaten banjarnegara', TRUE),
    ('banjarnegara', 'kab banjarnegara', TRUE),
    ('banjarnegara', 'kota banjarnegara', TRUE),
    ('banyumas', 'banyumas', FALSE),
    ('banyumas', 'kabupaten banyumas', TRUE),
    ('banyumas', 'kab banyumas', TRUE),
    ('banyumas', 'kota banyumas', TRUE),
    ('batang', 'batang', FALSE),
    ('batang', 'kabupaten batang', TRUE),
    ('batang', 'kab batang', TRUE),
    ('batang', 'kota batang', TRUE),
    ('blora', 'blora', FALSE),
    ('blora', 'kabupaten blora', TRUE),
    ('blora', 'kab blora', TRUE),
    ('blora', 'kota blora', TRUE),
    ('boyolali', 'boyolali', FALSE),
    ('boyolali', 'kabupaten boyolali', TRUE),
    ('boyolali', 'kab boyolali', TRUE),
    ('boyolali', 'kota boyolali', TRUE),
    ('brebes', 'brebes', FALSE),
    ('brebes', 'kabupaten brebes', TRUE),
    ('brebes', 'kab brebes', TRUE),
    ('brebes', 'kota brebes', TRUE),
    ('demak', 'demak', FALSE),
    ('demak', 'kabupaten demak', TRUE),
    ('demak', 'kab demak', TRUE),
    ('demak', 'kota demak', TRUE),
    ('grobogan', 'grobogan', FALSE),
    ('grobogan', 'kabupaten grobogan', TRUE),
    ('grobogan', 'kab grobogan', TRUE),
    ('grobogan', 'kota grobogan', TRUE),
    ('jepara', 'jepara', FALSE),
    ('jepara', 'kabupaten jepara', TRUE),
    ('jepara', 'kab jepara', TRUE),
    ('jepara', 'kota jepara', TRUE),
    ('karanganyar', 'karanganyar', FALSE),
    ('karanganyar', 'kabupaten karanganyar', TRUE),
    ('karanganyar', 'kab karanganyar', TRUE),
    ('karanganyar', 'kota karanganyar', TRUE),
    ('kebumen', 'kebumen', FALSE),
    ('kebumen', 'kabupaten kebumen', TRUE),
    ('kebumen', 'kab kebumen', TRUE),
    ('kebumen', 'kota kebumen', TRUE),
    ('kendal', 'kendal', FALSE),
    ('kendal', 'kabupaten kendal', TRUE),
    ('kendal', 'kab kendal', TRUE),
    ('kendal', 'kota kendal', TRUE),
    ('klaten', 'klaten', FALSE),
    ('klaten', 'kabupaten klaten', TRUE),
    ('klaten', 'kab klaten', TRUE),
    ('klaten', 'kota klaten', TRUE),
    ('kudus', 'kudus', FALSE),
    ('kudus', 'kabupaten kudus', TRUE),
    ('kudus', 'kab kudus', TRUE),
    ('kudus', 'kota kudus', TRUE),
    ('magelang', 'magelang', FALSE),
    ('magelang', 'kabupaten magelang', TRUE),
    ('magelang', 'kab magelang', TRUE),
    ('magelang', 'kota magelang', TRUE),
    ('pati', 'pati', FALSE),
    ('pati', 'kabupaten pati', TRUE),
    ('pati', 'kab pati', TRUE),
    ('pati', 'kota pati', TRUE),
    ('pekalongan', 'pekalongan', FALSE),
    ('pekalongan', 'kabupaten pekalongan', TRUE),
    ('pekalongan', 'kab pekalongan', TRUE),
    ('pekalongan', 'kota pekalongan', TRUE),
    ('pemalang', 'pemalang', FALSE),
    ('pemalang', 'kabupaten pemalang', TRUE),
    ('pemalang', 'kab pemalang', TRUE),
    ('pemalang', 'kota pemalang', TRUE),
    ('purbalingga', 'purbalingga', FALSE),
    ('purbalingga', 'kabupaten purbalingga', TRUE),
    ('purbalingga', 'kab purbalingga', TRUE),
    ('purbalingga', 'kota purbalingga', TRUE),
    ('purworejo', 'purworejo', FALSE),
    ('purworejo', 'kabupaten purworejo', TRUE),
    ('purworejo', 'kab purworejo', TRUE),
    ('purworejo', 'kota purworejo', TRUE),
    ('rembang', 'rembang', FALSE),
    ('rembang', 'kabupaten rembang', TRUE),
    ('rembang', 'kab rembang', TRUE),
    ('rembang', 'kota rembang', TRUE),
    ('semarang', 'semarang', FALSE),
    ('semarang', 'kabupaten semarang', TRUE),
    ('semarang', 'kab semarang', TRUE),
    ('semarang', 'kota semarang', TRUE),
    ('sragen', 'sragen', FALSE),
    ('sragen', 'kabupaten sragen', TRUE),
    ('sragen', 'kab sragen', TRUE),
    ('sragen', 'kota sragen', TRUE),
    ('sukoharjo', 'sukoharjo', FALSE),
    ('sukoharjo', 'kabupaten sukoharjo', TRUE),
    ('sukoharjo', 'kab sukoharjo', TRUE),
    ('sukoharjo', 'kota sukoharjo', TRUE),
    ('temanggung', 'temanggung', FALSE),
    ('temanggung', 'kabupaten temanggung', TRUE),
    ('temanggung', 'kab temanggung', TRUE),
    ('temanggung', 'kota temanggung', TRUE),
    ('wonogiri', 'wonogiri', FALSE),
    ('wonogiri', 'kabupaten wonogiri', TRUE),
    ('wonogiri', 'kab wonogiri', TRUE),
    ('wonogiri', 'kota wonogiri', TRUE),
    ('wonosobo', 'wonosobo', FALSE),
    ('wonosobo', 'kabupaten wonosobo', TRUE),
    ('wonosobo', 'kab wonosobo', TRUE),
    ('wonosobo', 'kota wonosobo', TRUE),
    ('salatiga', 'salatiga', FALSE),
    ('salatiga', 'kabupaten salatiga', TRUE),
    ('salatiga', 'kab salatiga', TRUE),
    ('salatiga', 'kota salatiga', TRUE),
    ('surakarta', 'surakarta', FALSE),
    ('surakarta', 'kabupaten surakarta', TRUE),
    ('surakarta', 'kab surakarta', TRUE),
    ('surakarta', 'kota surakarta', TRUE),
    ('tegal', 'tegal', FALSE),
    ('tegal', 'kabupaten tegal', TRUE),
    ('tegal', 'kab tegal', TRUE),
    ('tegal', 'kota tegal', TRUE),
    ('bantul', 'bantul', FALSE),
    ('bantul', 'kabupaten bantul', TRUE),
    ('bantul', 'kab bantul', TRUE),
    ('bantul', 'kota bantul', TRUE),
    ('gunung kidul', 'gunung kidul', FALSE),
    ('gunung kidul', 'kabupaten gunung kidul', TRUE),
    ('gunung kidul', 'kab gunung kidul', TRUE),
    ('gunung kidul', 'kota gunung kidul', TRUE),
    ('kulon progo', 'kulon progo', FALSE),
    ('kulon progo', 'kabupaten kulon progo', TRUE),
    ('kulon progo', 'kab kulon progo', TRUE),
    ('kulon progo', 'kota kulon progo', TRUE),
    ('sleman', 'sleman', FALSE),
    ('sleman', 'kabupaten sleman', TRUE),
    ('sleman', 'kab sleman', TRUE),
    ('sleman', 'kota sleman', TRUE),
    ('yogyakarta', 'yogyakarta', FALSE),
    ('yogyakarta', 'kabupaten yogyakarta', TRUE),
    ('yogyakarta', 'kab yogyakarta', TRUE),
    ('yogyakarta', 'kota yogyakarta', TRUE),
    ('bangkalan', 'bangkalan', FALSE),
    ('bangkalan', 'kabupaten bangkalan', TRUE),
    ('bangkalan', 'kab bangkalan', TRUE),
    ('bangkalan', 'kota bangkalan', TRUE),
    ('banyuwangi', 'banyuwangi', FALSE),
    ('banyuwangi', 'kabupaten banyuwangi', TRUE),
    ('banyuwangi', 'kab banyuwangi', TRUE),
    ('banyuwangi', 'kota banyuwangi', TRUE),
    ('blitar', 'blitar', FALSE),
    ('blitar', 'kabupaten blitar', TRUE),
    ('blitar', 'kab blitar', TRUE),
    ('blitar', 'kota blitar', TRUE),
    ('bojonegoro', 'bojonegoro', FALSE),
    ('bojonegoro', 'kabupaten bojonegoro', TRUE),
    ('bojonegoro', 'kab bojonegoro', TRUE),
    ('bojonegoro', 'kota bojonegoro', TRUE),
    ('bondowoso', 'bondowoso', FALSE),
    ('bondowoso', 'kabupaten bondowoso', TRUE),
    ('bondowoso', 'kab bondowoso', TRUE),
    ('bondowoso', 'kota bondowoso', TRUE),
    ('gresik', 'gresik', FALSE),
    ('gresik', 'kabupaten gresik', TRUE),
    ('gresik', 'kab gresik', TRUE),
    ('gresik', 'kota gresik', TRUE),
    ('jember', 'jember', FALSE),
    ('jember', 'kabupaten jember', TRUE),
    ('jember', 'kab jember', TRUE),
    ('jember', 'kota jember', TRUE),
    ('jombang', 'jombang', FALSE),
    ('jombang', 'kabupaten jombang', TRUE),
    ('jombang', 'kab jombang', TRUE),
    ('jombang', 'kota jombang', TRUE),
    ('kediri', 'kediri', FALSE),
    ('kediri', 'kabupaten kediri', TRUE),
    ('kediri', 'kab kediri', TRUE),
    ('kediri', 'kota kediri', TRUE),
    ('lamongan', 'lamongan', FALSE),
    ('lamongan', 'kabupaten lamongan', TRUE),
    ('lamongan', 'kab lamongan', TRUE),
    ('lamongan', 'kota lamongan', TRUE),
    ('lumajang', 'lumajang', FALSE),
    ('lumajang', 'kabupaten lumajang', TRUE),
    ('lumajang', 'kab lumajang', TRUE),
    ('lumajang', 'kota lumajang', TRUE),
    ('madiun', 'madiun', FALSE),
    ('madiun', 'kabupaten madiun', TRUE),
    ('madiun', 'kab madiun', TRUE),
    ('madiun', 'kota madiun', TRUE),
    ('magetan', 'magetan', FALSE),
    ('magetan', 'kabupaten magetan', TRUE),
    ('magetan', 'kab magetan', TRUE),
    ('magetan', 'kota magetan', TRUE),
    ('malang', 'malang', FALSE),
    ('malang', 'kabupaten malang', TRUE),
    ('malang', 'kab malang', TRUE),
    ('malang', 'kota malang', TRUE),
    ('mojokerto', 'mojokerto', FALSE),
    ('mojokerto', 'kabupaten mojokerto', TRUE),
    ('mojokerto', 'kab mojokerto', TRUE),
    ('mojokerto', 'kota mojokerto', TRUE),
    ('ngawi', 'ngawi', FALSE),
    ('ngawi', 'kabupaten ngawi', TRUE),
    ('ngawi', 'kab ngawi', TRUE),
    ('ngawi', 'kota ngawi', TRUE),
    ('pacitan', 'pacitan', FALSE),
    ('pacitan', 'kabupaten pacitan', TRUE),
    ('pacitan', 'kab pacitan', TRUE),
    ('pacitan', 'kota pacitan', TRUE),
    ('pamekasan', 'pamekasan', FALSE),
    ('pamekasan', 'kabupaten pamekasan', TRUE),
    ('pamekasan', 'kab pamekasan', TRUE),
    ('pamekasan', 'kota pamekasan', TRUE),
    ('pasuruan', 'pasuruan', FALSE),
    ('pasuruan', 'kabupaten pasuruan', TRUE),
    ('pasuruan', 'kab pasuruan', TRUE),
    ('pasuruan', 'kota pasuruan', TRUE),
    ('ponorogo', 'ponorogo', FALSE),
    ('ponorogo', 'kabupaten ponorogo', TRUE),
    ('ponorogo', 'kab ponorogo', TRUE),
    ('ponorogo', 'kota ponorogo', TRUE),
    ('probolinggo', 'probolinggo', FALSE),
    ('probolinggo', 'kabupaten probolinggo', TRUE),
    ('probolinggo', 'kab probolinggo', TRUE),
    ('probolinggo', 'kota probolinggo', TRUE),
    ('sampang', 'sampang', FALSE),
    ('sampang', 'kabupaten sampang', TRUE),
    ('sampang', 'kab sampang', TRUE),
    ('sampang', 'kota sampang', TRUE),
    ('sidoarjo', 'sidoarjo', FALSE),
    ('sidoarjo', 'kabupaten sidoarjo', TRUE),
    ('sidoarjo', 'kab sidoarjo', TRUE),
    ('sidoarjo', 'kota sidoarjo', TRUE),
    ('situbondo', 'situbondo', FALSE),
    ('situbondo', 'kabupaten situbondo', TRUE),
    ('situbondo', 'kab situbondo', TRUE),
    ('situbondo', 'kota situbondo', TRUE),
    ('sumenep', 'sumenep', FALSE),
    ('sumenep', 'kabupaten sumenep', TRUE),
    ('sumenep', 'kab sumenep', TRUE),
    ('sumenep', 'kota sumenep', TRUE),
    ('trenggalek', 'trenggalek', FALSE),
    ('trenggalek', 'kabupaten trenggalek', TRUE),
    ('trenggalek', 'kab trenggalek', TRUE),
    ('trenggalek', 'kota trenggalek', TRUE),
    ('tuban', 'tuban', FALSE),
    ('tuban', 'kabupaten tuban', TRUE),
    ('tuban', 'kab tuban', TRUE),
    ('tuban', 'kota tuban', TRUE),
    ('tulungagung', 'tulungagung', FALSE),
    ('tulungagung', 'kabupaten tulungagung', TRUE),
    ('tulungagung', 'kab tulungagung', TRUE),
    ('tulungagung', 'kota tulungagung', TRUE),
    ('batu', 'batu', FALSE),
    ('batu', 'kabupaten batu', TRUE),
    ('batu', 'kab batu', TRUE),
    ('batu', 'kota batu', TRUE),
    ('surabaya', 'surabaya', FALSE),
    ('surabaya', 'kabupaten surabaya', TRUE),
    ('surabaya', 'kab surabaya', TRUE),
    ('surabaya', 'kota surabaya', TRUE),
    ('lebak', 'lebak', FALSE),
    ('lebak', 'kabupaten lebak', TRUE),
    ('lebak', 'kab lebak', TRUE),
    ('lebak', 'kota lebak', TRUE),
    ('pandeglang', 'pandeglang', FALSE),
    ('pandeglang', 'kabupaten pandeglang', TRUE),
    ('pandeglang', 'kab pandeglang', TRUE),
    ('pandeglang', 'kota pandeglang', TRUE),
    ('serang', 'serang', FALSE),
    ('serang', 'kabupaten serang', TRUE),
    ('serang', 'kab serang', TRUE),
    ('serang', 'kota serang', TRUE),
    ('tangerang', 'tangerang', FALSE),
    ('tangerang', 'kabupaten tangerang', TRUE),
    ('tangerang', 'kab tangerang', TRUE),
    ('tangerang', 'kota tangerang', TRUE),
    ('cilegon', 'cilegon', FALSE),
    ('cilegon', 'kabupaten cilegon', TRUE),
    ('cilegon', 'kab cilegon', TRUE),
    ('cilegon', 'kota cilegon', TRUE),
    ('tangerang selatan', 'tangerang selatan', FALSE),
    ('tangerang selatan', 'kabupaten tangerang selatan', TRUE),
    ('tangerang selatan', 'kab tangerang selatan', TRUE),
    ('tangerang selatan', 'kota tangerang selatan', TRUE),
    ('badung', 'badung', FALSE),
    ('badung', 'kabupaten badung', TRUE),
    ('badung', 'kab badung', TRUE),
    ('badung', 'kota badung', TRUE),
    ('bangli', 'bangli', FALSE),
    ('bangli', 'kabupaten bangli', TRUE),
    ('bangli', 'kab bangli', TRUE),
    ('bangli', 'kota bangli', TRUE),
    ('buleleng', 'buleleng', FALSE),
    ('buleleng', 'kabupaten buleleng', TRUE),
    ('buleleng', 'kab buleleng', TRUE),
    ('buleleng', 'kota buleleng', TRUE),
    ('gianyar', 'gianyar', FALSE),
    ('gianyar', 'kabupaten gianyar', TRUE),
    ('gianyar', 'kab gianyar', TRUE),
    ('gianyar', 'kota gianyar', TRUE),
    ('jembrana', 'jembrana', FALSE),
    ('jembrana', 'kabupaten jembrana', TRUE),
    ('jembrana', 'kab jembrana', TRUE),
    ('jembrana', 'kota jembrana', TRUE),
    ('karangasem', 'karangasem', FALSE),
    ('karangasem', 'kabupaten karangasem', TRUE),
    ('karangasem', 'kab karangasem', TRUE),
    ('karangasem', 'kota karangasem', TRUE),
    ('klungkung', 'klungkung', FALSE),
    ('klungkung', 'kabupaten klungkung', TRUE),
    ('klungkung', 'kab klungkung', TRUE),
    ('klungkung', 'kota klungkung', TRUE),
    ('tabanan', 'tabanan', FALSE),
    ('tabanan', 'kabupaten tabanan', TRUE),
    ('tabanan', 'kab tabanan', TRUE),
    ('tabanan', 'kota tabanan', TRUE),
    ('denpasar', 'denpasar', FALSE),
    ('denpasar', 'kabupaten denpasar', TRUE),
    ('denpasar', 'kab denpasar', TRUE),
    ('denpasar', 'kota denpasar', TRUE),
    ('bima', 'bima', FALSE),
    ('bima', 'kabupaten bima', TRUE),
    ('bima', 'kab bima', TRUE),
    ('bima', 'kota bima', TRUE),
    ('dompu', 'dompu', FALSE),
    ('dompu', 'kabupaten dompu', TRUE),
    ('dompu', 'kab dompu', TRUE),
    ('dompu', 'kota dompu', TRUE),
    ('lombok barat', 'lombok barat', FALSE),
    ('lombok barat', 'kabupaten lombok barat', TRUE),
    ('lombok barat', 'kab lombok barat', TRUE),
    ('lombok barat', 'kota lombok barat', TRUE),
    ('lombok tengah', 'lombok tengah', FALSE),
    ('lombok tengah', 'kabupaten lombok tengah', TRUE),
    ('lombok tengah', 'kab lombok tengah', TRUE),
    ('lombok tengah', 'kota lombok tengah', TRUE),
    ('lombok timur', 'lombok timur', FALSE),
    ('lombok timur', 'kabupaten lombok timur', TRUE),
    ('lombok timur', 'kab lombok timur', TRUE),
    ('lombok timur', 'kota lombok timur', TRUE),
    ('lombok utara', 'lombok utara', FALSE),
    ('lombok utara', 'kabupaten lombok utara', TRUE),
    ('lombok utara', 'kab lombok utara', TRUE),
    ('lombok utara', 'kota lombok utara', TRUE),
    ('sumbawa', 'sumbawa', FALSE),
    ('sumbawa', 'kabupaten sumbawa', TRUE),
    ('sumbawa', 'kab sumbawa', TRUE),
    ('sumbawa', 'kota sumbawa', TRUE),
    ('sumbawa barat', 'sumbawa barat', FALSE),
    ('sumbawa barat', 'kabupaten sumbawa barat', TRUE),
    ('sumbawa barat', 'kab sumbawa barat', TRUE),
    ('sumbawa barat', 'kota sumbawa barat', TRUE),
    ('mataram', 'mataram', FALSE),
    ('mataram', 'kabupaten mataram', TRUE),
    ('mataram', 'kab mataram', TRUE),
    ('mataram', 'kota mataram', TRUE),
    ('alor', 'alor', FALSE),
    ('alor', 'kabupaten alor', TRUE),
    ('alor', 'kab alor', TRUE),
    ('alor', 'kota alor', TRUE),
    ('belu', 'belu', FALSE),
    ('belu', 'kabupaten belu', TRUE),
    ('belu', 'kab belu', TRUE),
    ('belu', 'kota belu', TRUE),
    ('ende', 'ende', FALSE),
    ('ende', 'kabupaten ende', TRUE),
    ('ende', 'kab ende', TRUE),
    ('ende', 'kota ende', TRUE),
    ('flores timur', 'flores timur', FALSE),
    ('flores timur', 'kabupaten flores timur', TRUE),
    ('flores timur', 'kab flores timur', TRUE),
    ('flores timur', 'kota flores timur', TRUE),
    ('kupang', 'kupang', FALSE),
    ('kupang', 'kabupaten kupang', TRUE),
    ('kupang', 'kab kupang', TRUE),
    ('kupang', 'kota kupang', TRUE),
    ('lembata', 'lembata', FALSE),
    ('lembata', 'kabupaten lembata', TRUE),
    ('lembata', 'kab lembata', TRUE),
    ('lembata', 'kota lembata', TRUE),
    ('malaka', 'malaka', FALSE),
    ('malaka', 'kabupaten malaka', TRUE),
    ('malaka', 'kab malaka', TRUE),
    ('malaka', 'kota malaka', TRUE),
    ('manggarai', 'manggarai', FALSE),
    ('manggarai', 'kabupaten manggarai', TRUE),
    ('manggarai', 'kab manggarai', TRUE),
    ('manggarai', 'kota manggarai', TRUE),
    ('manggarai barat', 'manggarai barat', FALSE),
    ('manggarai barat', 'kabupaten manggarai barat', TRUE),
    ('manggarai barat', 'kab manggarai barat', TRUE),
    ('manggarai barat', 'kota manggarai barat', TRUE),
    ('manggarai timur', 'manggarai timur', FALSE),
    ('manggarai timur', 'kabupaten manggarai timur', TRUE),
    ('manggarai timur', 'kab manggarai timur', TRUE),
    ('manggarai timur', 'kota manggarai timur', TRUE),
    ('nagekeo', 'nagekeo', FALSE),
    ('nagekeo', 'kabupaten nagekeo', TRUE),
    ('nagekeo', 'kab nagekeo', TRUE),
    ('nagekeo', 'kota nagekeo', TRUE),
    ('ngada', 'ngada', FALSE),
    ('ngada', 'kabupaten ngada', TRUE),
    ('ngada', 'kab ngada', TRUE),
    ('ngada', 'kota ngada', TRUE),
    ('rote ndao', 'rote ndao', FALSE),
    ('rote ndao', 'kabupaten rote ndao', TRUE),
    ('rote ndao', 'kab rote ndao', TRUE),
    ('rote ndao', 'kota rote ndao', TRUE),
    ('sabu raijua', 'sabu raijua', FALSE),
    ('sabu raijua', 'kabupaten sabu raijua', TRUE),
    ('sabu raijua', 'kab sabu raijua', TRUE),
    ('sabu raijua', 'kota sabu raijua', TRUE),
    ('sikka', 'sikka', FALSE),
    ('sikka', 'kabupaten sikka', TRUE),
    ('sikka', 'kab sikka', TRUE),
    ('sikka', 'kota sikka', TRUE),
    ('sumba barat', 'sumba barat', FALSE),
    ('sumba barat', 'kabupaten sumba barat', TRUE),
    ('sumba barat', 'kab sumba barat', TRUE),
    ('sumba barat', 'kota sumba barat', TRUE),
    ('sumba barat daya', 'sumba barat daya', FALSE),
    ('sumba barat daya', 'kabupaten sumba barat daya', TRUE),
    ('sumba barat daya', 'kab sumba barat daya', TRUE),
    ('sumba barat daya', 'kota sumba barat daya', TRUE),
    ('sumba tengah', 'sumba tengah', FALSE),
    ('sumba tengah', 'kabupaten sumba tengah', TRUE),
    ('sumba tengah', 'kab sumba tengah', TRUE),
    ('sumba tengah', 'kota sumba tengah', TRUE),
    ('sumba timur', 'sumba timur', FALSE),
    ('sumba timur', 'kabupaten sumba timur', TRUE),
    ('sumba timur', 'kab sumba timur', TRUE),
    ('sumba timur', 'kota sumba timur', TRUE),
    ('timor tengah selatan', 'timor tengah selatan', FALSE),
    ('timor tengah selatan', 'kabupaten timor tengah selatan', TRUE),
    ('timor tengah selatan', 'kab timor tengah selatan', TRUE),
    ('timor tengah selatan', 'kota timor tengah selatan', TRUE),
    ('timor tengah utara', 'timor tengah utara', FALSE),
    ('timor tengah utara', 'kabupaten timor tengah utara', TRUE),
    ('timor tengah utara', 'kab timor tengah utara', TRUE),
    ('timor tengah utara', 'kota timor tengah utara', TRUE),
    ('bengkayang', 'bengkayang', FALSE),
    ('bengkayang', 'kabupaten bengkayang', TRUE),
    ('bengkayang', 'kab bengkayang', TRUE),
    ('bengkayang', 'kota bengkayang', TRUE),
    ('kapuas hulu', 'kapuas hulu', FALSE),
    ('kapuas hulu', 'kabupaten kapuas hulu', TRUE),
    ('kapuas hulu', 'kab kapuas hulu', TRUE),
    ('kapuas hulu', 'kota kapuas hulu', TRUE),
    ('kayong utara', 'kayong utara', FALSE),
    ('kayong utara', 'kabupaten kayong utara', TRUE),
    ('kayong utara', 'kab kayong utara', TRUE),
    ('kayong utara', 'kota kayong utara', TRUE),
    ('ketapang', 'ketapang', FALSE),
    ('ketapang', 'kabupaten ketapang', TRUE),
    ('ketapang', 'kab ketapang', TRUE),
    ('ketapang', 'kota ketapang', TRUE),
    ('kubu raya', 'kubu raya', FALSE),
    ('kubu raya', 'kabupaten kubu raya', TRUE),
    ('kubu raya', 'kab kubu raya', TRUE),
    ('kubu raya', 'kota kubu raya', TRUE),
    ('landak', 'landak', FALSE),
    ('landak', 'kabupaten landak', TRUE),
    ('landak', 'kab landak', TRUE),
    ('landak', 'kota landak', TRUE),
    ('melawi', 'melawi', FALSE),
    ('melawi', 'kabupaten melawi', TRUE),
    ('melawi', 'kab melawi', TRUE),
    ('melawi', 'kota melawi', TRUE),
    ('mempawah', 'mempawah', FALSE),
    ('mempawah', 'kabupaten mempawah', TRUE),
    ('mempawah', 'kab mempawah', TRUE),
    ('mempawah', 'kota mempawah', TRUE),
    ('sambas', 'sambas', FALSE),
    ('sambas', 'kabupaten sambas', TRUE),
    ('sambas', 'kab sambas', TRUE),
    ('sambas', 'kota sambas', TRUE),
    ('sanggau', 'sanggau', FALSE),
    ('sanggau', 'kabupaten sanggau', TRUE),
    ('sanggau', 'kab sanggau', TRUE),
    ('sanggau', 'kota sanggau', TRUE),
    ('sintang', 'sintang', FALSE),
    ('sintang', 'kabupaten sintang', TRUE),
    ('sintang', 'kab sintang', TRUE),
    ('sintang', 'kota sintang', TRUE),
    ('pontianak', 'pontianak', FALSE),
    ('pontianak', 'kabupaten pontianak', TRUE),
    ('pontianak', 'kab pontianak', TRUE),
    ('pontianak', 'kota pontianak', TRUE),
    ('singkawang', 'singkawang', FALSE),
    ('singkawang', 'kabupaten singkawang', TRUE),
    ('singkawang', 'kab singkawang', TRUE),
    ('singkawang', 'kota singkawang', TRUE),
    ('barito selatan', 'barito selatan', FALSE),
    ('barito selatan', 'kabupaten barito selatan', TRUE),
    ('barito selatan', 'kab barito selatan', TRUE),
    ('barito selatan', 'kota barito selatan', TRUE),
    ('barito timur', 'barito timur', FALSE),
    ('barito timur', 'kabupaten barito timur', TRUE),
    ('barito timur', 'kab barito timur', TRUE),
    ('barito timur', 'kota barito timur', TRUE),
    ('barito utara', 'barito utara', FALSE),
    ('barito utara', 'kabupaten barito utara', TRUE),
    ('barito utara', 'kab barito utara', TRUE),
    ('barito utara', 'kota barito utara', TRUE),
    ('gunung mas', 'gunung mas', FALSE),
    ('gunung mas', 'kabupaten gunung mas', TRUE),
    ('gunung mas', 'kab gunung mas', TRUE),
    ('gunung mas', 'kota gunung mas', TRUE),
    ('kapuas', 'kapuas', FALSE),
    ('kapuas', 'kabupaten kapuas', TRUE),
    ('kapuas', 'kab kapuas', TRUE),
    ('kapuas', 'kota kapuas', TRUE),
    ('katingan', 'katingan', FALSE),
    ('katingan', 'kabupaten katingan', TRUE),
    ('katingan', 'kab katingan', TRUE),
    ('katingan', 'kota katingan', TRUE),
    ('kotawaringin barat', 'kotawaringin barat', FALSE),
    ('kotawaringin barat', 'kabupaten kotawaringin barat', TRUE),
    ('kotawaringin barat', 'kab kotawaringin barat', TRUE),
    ('kotawaringin barat', 'kota kotawaringin barat', TRUE),
    ('kotawaringin timur', 'kotawaringin timur', FALSE),
    ('kotawaringin timur', 'kabupaten kotawaringin timur', TRUE),
    ('kotawaringin timur', 'kab kotawaringin timur', TRUE),
    ('kotawaringin timur', 'kota kotawaringin timur', TRUE),
    ('lamandau', 'lamandau', FALSE),
    ('lamandau', 'kabupaten lamandau', TRUE),
    ('lamandau', 'kab lamandau', TRUE),
    ('lamandau', 'kota lamandau', TRUE),
    ('murung raya', 'murung raya', FALSE),
    ('murung raya', 'kabupaten murung raya', TRUE),
    ('murung raya', 'kab murung raya', TRUE),
    ('murung raya', 'kota murung raya', TRUE),
    ('pulang pisau', 'pulang pisau', FALSE),
    ('pulang pisau', 'kabupaten pulang pisau', TRUE),
    ('pulang pisau', 'kab pulang pisau', TRUE),
    ('pulang pisau', 'kota pulang pisau', TRUE),
    ('sukamara', 'sukamara', FALSE),
    ('sukamara', 'kabupaten sukamara', TRUE),
    ('sukamara', 'kab sukamara', TRUE),
    ('sukamara', 'kota sukamara', TRUE),
    ('seruyan', 'seruyan', FALSE),
    ('seruyan', 'kabupaten seruyan', TRUE),
    ('seruyan', 'kab seruyan', TRUE),
    ('seruyan', 'kota seruyan', TRUE),
    ('palangkaraya', 'palangkaraya', FALSE),
    ('palangkaraya', 'kabupaten palangkaraya', TRUE),
    ('palangkaraya', 'kab palangkaraya', TRUE),
    ('palangkaraya', 'kota palangkaraya', TRUE),
    ('balangan', 'balangan', FALSE),
    ('balangan', 'kabupaten balangan', TRUE),
    ('balangan', 'kab balangan', TRUE),
    ('balangan', 'kota balangan', TRUE),
    ('barito kuala', 'barito kuala', FALSE),
    ('barito kuala', 'kabupaten barito kuala', TRUE),
    ('barito kuala', 'kab barito kuala', TRUE),
    ('barito kuala', 'kota barito kuala', TRUE),
    ('hulu sungai selatan', 'hulu sungai selatan', FALSE),
    ('hulu sungai selatan', 'kabupaten hulu sungai selatan', TRUE),
    ('hulu sungai selatan', 'kab hulu sungai selatan', TRUE),
    ('hulu sungai selatan', 'kota hulu sungai selatan', TRUE),
    ('hulu sungai tengah', 'hulu sungai tengah', FALSE),
    ('hulu sungai tengah', 'kabupaten hulu sungai tengah', TRUE),
    ('hulu sungai tengah', 'kab hulu sungai tengah', TRUE),
    ('hulu sungai tengah', 'kota hulu sungai tengah', TRUE),
    ('hulu sungai utara', 'hulu sungai utara', FALSE),
    ('hulu sungai utara', 'kabupaten hulu sungai utara', TRUE),
    ('hulu sungai utara', 'kab hulu sungai utara', TRUE),
    ('hulu sungai utara', 'kota hulu sungai utara', TRUE),
    ('kotabaru', 'kotabaru', FALSE),
    ('kotabaru', 'kabupaten kotabaru', TRUE),
    ('kotabaru', 'kab kotabaru', TRUE),
    ('kotabaru', 'kota kotabaru', TRUE),
    ('tabalong', 'tabalong', FALSE),
    ('tabalong', 'kabupaten tabalong', TRUE),
    ('tabalong', 'kab tabalong', TRUE),
    ('tabalong', 'kota tabalong', TRUE),
    ('tanah bumbu', 'tanah bumbu', FALSE),
    ('tanah bumbu', 'kabupaten tanah bumbu', TRUE),
    ('tanah bumbu', 'kab tanah bumbu', TRUE),
    ('tanah bumbu', 'kota tanah bumbu', TRUE),
    ('tanah laut', 'tanah laut', FALSE),
    ('tanah laut', 'kabupaten tanah laut', TRUE),
    ('tanah laut', 'kab tanah laut', TRUE),
    ('tanah laut', 'kota tanah laut', TRUE),
    ('tapin', 'tapin', FALSE),
    ('tapin', 'kabupaten tapin', TRUE),
    ('tapin', 'kab tapin', TRUE),
    ('tapin', 'kota tapin', TRUE),
    ('banjarbaru', 'banjarbaru', FALSE),
    ('banjarbaru', 'kabupaten banjarbaru', TRUE),
    ('banjarbaru', 'kab banjarbaru', TRUE),
    ('banjarbaru', 'kota banjarbaru', TRUE),
    ('banjarmasin', 'banjarmasin', FALSE),
    ('banjarmasin', 'kabupaten banjarmasin', TRUE),
    ('banjarmasin', 'kab banjarmasin', TRUE),
    ('banjarmasin', 'kota banjarmasin', TRUE),
    ('berau', 'berau', FALSE),
    ('berau', 'kabupaten berau', TRUE),
    ('berau', 'kab berau', TRUE),
    ('berau', 'kota berau', TRUE),
    ('kutai barat', 'kutai barat', FALSE),
    ('kutai barat', 'kabupaten kutai barat', TRUE),
    ('kutai barat', 'kab kutai barat', TRUE),
    ('kutai barat', 'kota kutai barat', TRUE),
    ('kutai kartanegara', 'kutai kartanegara', FALSE),
    ('kutai kartanegara', 'kabupaten kutai kartanegara', TRUE),
    ('kutai kartanegara', 'kab kutai kartanegara', TRUE),
    ('kutai kartanegara', 'kota kutai kartanegara', TRUE),
    ('kutai timur', 'kutai timur', FALSE),
    ('kutai timur', 'kabupaten kutai timur', TRUE),
    ('kutai timur', 'kab kutai timur', TRUE),
    ('kutai timur', 'kota kutai timur', TRUE),
    ('mahakam ulu', 'mahakam ulu', FALSE),
    ('mahakam ulu', 'kabupaten mahakam ulu', TRUE),
    ('mahakam ulu', 'kab mahakam ulu', TRUE),
    ('mahakam ulu', 'kota mahakam ulu', TRUE),
    ('paser', 'paser', FALSE),
    ('paser', 'kabupaten paser', TRUE),
    ('paser', 'kab paser', TRUE),
    ('paser', 'kota paser', TRUE),
    ('penajam paser utara', 'penajam paser utara', FALSE),
    ('penajam paser utara', 'kabupaten penajam paser utara', TRUE),
    ('penajam paser utara', 'kab penajam paser utara', TRUE),
    ('penajam paser utara', 'kota penajam paser utara', TRUE),
    ('balikpapan', 'balikpapan', FALSE),
    ('balikpapan', 'kabupaten balikpapan', TRUE),
    ('balikpapan', 'kab balikpapan', TRUE),
    ('balikpapan', 'kota balikpapan', TRUE),
    ('bontang', 'bontang', FALSE),
    ('bontang', 'kabupaten bontang', TRUE),
    ('bontang', 'kab bontang', TRUE),
    ('bontang', 'kota bontang', TRUE),
    ('samarinda', 'samarinda', FALSE),
    ('samarinda', 'kabupaten samarinda', TRUE),
    ('samarinda', 'kab samarinda', TRUE),
    ('samarinda', 'kota samarinda', TRUE),
    ('tarakan', 'tarakan', FALSE),
    ('tarakan', 'kabupaten tarakan', TRUE),
    ('tarakan', 'kab tarakan', TRUE),
    ('tarakan', 'kota tarakan', TRUE),
    ('bulungan', 'bulungan', FALSE),
    ('bulungan', 'kabupaten bulungan', TRUE),
    ('bulungan', 'kab bulungan', TRUE),
    ('bulungan', 'kota bulungan', TRUE),
    ('malinau', 'malinau', FALSE),
    ('malinau', 'kabupaten malinau', TRUE),
    ('malinau', 'kab malinau', TRUE),
    ('malinau', 'kota malinau', TRUE),
    ('nunukan', 'nunukan', FALSE),
    ('nunukan', 'kabupaten nunukan', TRUE),
    ('nunukan', 'kab nunukan', TRUE),
    ('nunukan', 'kota nunukan', TRUE),
    ('tana tidung', 'tana tidung', FALSE),
    ('tana tidung', 'kabupaten tana tidung', TRUE),
    ('tana tidung', 'kab tana tidung', TRUE),
    ('tana tidung', 'kota tana tidung', TRUE),
    ('bolaang mongondow', 'bolaang mongondow', FALSE),
    ('bolaang mongondow', 'kabupaten bolaang mongondow', TRUE),
    ('bolaang mongondow', 'kab bolaang mongondow', TRUE),
    ('bolaang mongondow', 'kota bolaang mongondow', TRUE),
    ('bolaang mongondow selatan', 'bolaang mongondow selatan', FALSE),
    ('bolaang mongondow selatan', 'kabupaten bolaang mongondow selatan', TRUE),
    ('bolaang mongondow selatan', 'kab bolaang mongondow selatan', TRUE),
    ('bolaang mongondow selatan', 'kota bolaang mongondow selatan', TRUE),
    ('bolaang mongondow timur', 'bolaang mongondow timur', FALSE),
    ('bolaang mongondow timur', 'kabupaten bolaang mongondow timur', TRUE),
    ('bolaang mongondow timur', 'kab bolaang mongondow timur', TRUE),
    ('bolaang mongondow timur', 'kota bolaang mongondow timur', TRUE),
    ('bolaang mongondow utara', 'bolaang mongondow utara', FALSE),
    ('bolaang mongondow utara', 'kabupaten bolaang mongondow utara', TRUE),
    ('bolaang mongondow utara', 'kab bolaang mongondow utara', TRUE),
    ('bolaang mongondow utara', 'kota bolaang mongondow utara', TRUE),
    ('kepulauan sangihe', 'kepulauan sangihe', FALSE),
    ('kepulauan sangihe', 'kabupaten kepulauan sangihe', TRUE),
    ('kepulauan sangihe', 'kab kepulauan sangihe', TRUE),
    ('kepulauan sangihe', 'kota kepulauan sangihe', TRUE),
    ('kepulauan siau tagulandang biaro (sitaro)', 'kepulauan siau tagulandang biaro (sitaro)', FALSE),
    ('kepulauan siau tagulandang biaro (sitaro)', 'kabupaten kepulauan siau tagulandang biaro (sitaro)', TRUE),
    ('kepulauan siau tagulandang biaro (sitaro)', 'kab kepulauan siau tagulandang biaro (sitaro)', TRUE),
    ('kepulauan siau tagulandang biaro (sitaro)', 'kota kepulauan siau tagulandang biaro (sitaro)', TRUE),
    ('kepulauan talaud', 'kepulauan talaud', FALSE),
    ('kepulauan talaud', 'kabupaten kepulauan talaud', TRUE),
    ('kepulauan talaud', 'kab kepulauan talaud', TRUE),
    ('kepulauan talaud', 'kota kepulauan talaud', TRUE),
    ('minahasa', 'minahasa', FALSE),
    ('minahasa', 'kabupaten minahasa', TRUE),
    ('minahasa', 'kab minahasa', TRUE),
    ('minahasa', 'kota minahasa', TRUE),
    ('minahasa selatan', 'minahasa selatan', FALSE),
    ('minahasa selatan', 'kabupaten minahasa selatan', TRUE),
    ('minahasa selatan', 'kab minahasa selatan', TRUE),
    ('minahasa selatan', 'kota minahasa selatan', TRUE),
    ('minahasa tenggara', 'minahasa tenggara', FALSE),
    ('minahasa tenggara', 'kabupaten minahasa tenggara', TRUE),
    ('minahasa tenggara', 'kab minahasa tenggara', TRUE),
    ('minahasa tenggara', 'kota minahasa tenggara', TRUE),
    ('minahasa utara', 'minahasa utara', FALSE),
    ('minahasa utara', 'kabupaten minahasa utara', TRUE),
    ('minahasa utara', 'kab minahasa utara', TRUE),
    ('minahasa utara', 'kota minahasa utara', TRUE),
    ('bitung', 'bitung', FALSE),
    ('bitung', 'kabupaten bitung', TRUE),
    ('bitung', 'kab bitung', TRUE),
    ('bitung', 'kota bitung', TRUE),
    ('kotamobagu', 'kotamobagu', FALSE),
    ('kotamobagu', 'kabupaten kotamobagu', TRUE),
    ('kotamobagu', 'kab kotamobagu', TRUE),
    ('kotamobagu', 'kota kotamobagu', TRUE),
    ('manado', 'manado', FALSE),
    ('manado', 'kabupaten manado', TRUE),
    ('manado', 'kab manado', TRUE),
    ('manado', 'kota manado', TRUE),
    ('tomohon', 'tomohon', FALSE),
    ('tomohon', 'kabupaten tomohon', TRUE),
    ('tomohon', 'kab tomohon', TRUE),
    ('tomohon', 'kota tomohon', TRUE),
    ('banggai', 'banggai', FALSE),
    ('banggai', 'kabupaten banggai', TRUE),
    ('banggai', 'kab banggai', TRUE),
    ('banggai', 'kota banggai', TRUE),
    ('banggai kepulauan', 'banggai kepulauan', FALSE),
    ('banggai kepulauan', 'kabupaten banggai kepulauan', TRUE),
    ('banggai kepulauan', 'kab banggai kepulauan', TRUE),
    ('banggai kepulauan', 'kota banggai kepulauan', TRUE),
    ('banggai laut', 'banggai laut', FALSE),
    ('banggai laut', 'kabupaten banggai laut', TRUE),
    ('banggai laut', 'kab banggai laut', TRUE),
    ('banggai laut', 'kota banggai laut', TRUE),
    ('buol', 'buol', FALSE),
    ('buol', 'kabupaten buol', TRUE),
    ('buol', 'kab buol', TRUE),
    ('buol', 'kota buol', TRUE),
    ('donggala', 'donggala', FALSE),
    ('donggala', 'kabupaten donggala', TRUE),
    ('donggala', 'kab donggala', TRUE),
    ('donggala', 'kota donggala', TRUE),
    ('morowali', 'morowali', FALSE),
    ('morowali', 'kabupaten morowali', TRUE),
    ('morowali', 'kab morowali', TRUE),
    ('morowali', 'kota morowali', TRUE),
    ('morowali utara', 'morowali utara', FALSE),
    ('morowali utara', 'kabupaten morowali utara', TRUE),
    ('morowali utara', 'kab morowali utara', TRUE),
    ('morowali utara', 'kota morowali utara', TRUE),
    ('pali', 'pali', FALSE),
    ('pali', 'kabupaten pali', TRUE),
    ('pali', 'kab pali', TRUE),
    ('pali', 'kota pali', TRUE),
    ('parigi moutong', 'parigi moutong', FALSE),
    ('parigi moutong', 'kabupaten parigi moutong', TRUE),
    ('parigi moutong', 'kab parigi moutong', TRUE),
    ('parigi moutong', 'kota parigi moutong', TRUE),
    ('poso', 'poso', FALSE),
    ('poso', 'kabupaten poso', TRUE),
    ('poso', 'kab poso', TRUE),
    ('poso', 'kota poso', TRUE),
    ('sigi', 'sigi', FALSE),
    ('sigi', 'kabupaten sigi', TRUE),
    ('sigi', 'kab sigi', TRUE),
    ('sigi', 'kota sigi', TRUE),
    ('tojo una-una', 'tojo una-una', FALSE),
    ('tojo una-una', 'kabupaten tojo una-una', TRUE),
    ('tojo una-una', 'kab tojo una-una', TRUE),
    ('tojo una-una', 'kota tojo una-una', TRUE),
    ('toli toli', 'toli toli', FALSE),
    ('toli toli', 'kabupaten toli toli', TRUE),
    ('toli toli', 'kab toli toli', TRUE),
    ('toli toli', 'kota toli toli', TRUE),
    ('palu', 'palu', FALSE),
    ('palu', 'kabupaten palu', TRUE),
    ('palu', 'kab palu', TRUE),
    ('palu', 'kota palu', TRUE),
    ('bantaeng', 'bantaeng', FALSE),
    ('bantaeng', 'kabupaten bantaeng', TRUE),
    ('bantaeng', 'kab bantaeng', TRUE),
    ('bantaeng', 'kota bantaeng', TRUE),
    ('barru', 'barru', FALSE),
    ('barru', 'kabupaten barru', TRUE),
    ('barru', 'kab barru', TRUE),
    ('barru', 'kota barru', TRUE),
    ('bone', 'bone', FALSE),
    ('bone', 'kabupaten bone', TRUE),
    ('bone', 'kab bone', TRUE),
    ('bone', 'kota bone', TRUE),
    ('bulukumba', 'bulukumba', FALSE),
    ('bulukumba', 'kabupaten bulukumba', TRUE),
    ('bulukumba', 'kab bulukumba', TRUE),
    ('bulukumba', 'kota bulukumba', TRUE),
    ('enrekang', 'enrekang', FALSE),
    ('enrekang', 'kabupaten enrekang', TRUE),
    ('enrekang', 'kab enrekang', TRUE),
    ('enrekang', 'kota enrekang', TRUE),
    ('gowa', 'gowa', FALSE),
    ('gowa', 'kabupaten gowa', TRUE),
    ('gowa', 'kab gowa', TRUE),
    ('gowa', 'kota gowa', TRUE),
    ('jeneponto', 'jeneponto', FALSE),
    ('jeneponto', 'kabupaten jeneponto', TRUE),
    ('jeneponto', 'kab jeneponto', TRUE),
    ('jeneponto', 'kota jeneponto', TRUE),
    ('kepulauan selayar', 'kepulauan selayar', FALSE),
    ('kepulauan selayar', 'kabupaten kepulauan selayar', TRUE),
    ('kepulauan selayar', 'kab kepulauan selayar', TRUE),
    ('kepulauan selayar', 'kota kepulauan selayar', TRUE),
    ('luwu', 'luwu', FALSE),
    ('luwu', 'kabupaten luwu', TRUE),
    ('luwu', 'kab luwu', TRUE),
    ('luwu', 'kota luwu', TRUE),
    ('luwu timur', 'luwu timur', FALSE),
    ('luwu timur', 'kabupaten luwu timur', TRUE),
    ('luwu timur', 'kab luwu timur', TRUE),
    ('luwu timur', 'kota luwu timur', TRUE),
    ('luwu utara', 'luwu utara', FALSE),
    ('luwu utara', 'kabupaten luwu utara', TRUE),
    ('luwu utara', 'kab luwu utara', TRUE),
    ('luwu utara', 'kota luwu utara', TRUE),
    ('maros', 'maros', FALSE),
    ('maros', 'kabupaten maros', TRUE),
    ('maros', 'kab maros', TRUE),
    ('maros', 'kota maros', TRUE),
    ('pangkajene kepulauan', 'pangkajene kepulauan', FALSE),
    ('pangkajene kepulauan', 'kabupaten pangkajene kepulauan', TRUE),
    ('pangkajene kepulauan', 'kab pangkajene kepulauan', TRUE),
    ('pangkajene kepulauan', 'kota pangkajene kepulauan', TRUE),
    ('pinrang', 'pinrang', FALSE),
    ('pinrang', 'kabupaten pinrang', TRUE),
    ('pinrang', 'kab pinrang', TRUE),
    ('pinrang', 'kota pinrang', TRUE),
    ('sidenreng rappang', 'sidenreng rappang', FALSE),
    ('sidenreng rappang', 'kabupaten sidenreng rappang', TRUE),
    ('sidenreng rappang', 'kab sidenreng rappang', TRUE),
    ('sidenreng rappang', 'kota sidenreng rappang', TRUE),
    ('sinjai', 'sinjai', FALSE),
    ('sinjai', 'kabupaten sinjai', TRUE),
    ('sinjai', 'kab sinjai', TRUE),
    ('sinjai', 'kota sinjai', TRUE),
    ('soppeng', 'soppeng', FALSE),
    ('soppeng', 'kabupaten soppeng', TRUE),
    ('soppeng', 'kab soppeng', TRUE),
    ('soppeng', 'kota soppeng', TRUE),
    ('takalar', 'takalar', FALSE),
    ('takalar', 'kabupaten takalar', TRUE),
    ('takalar', 'kab takalar', TRUE),
    ('takalar', 'kota takalar', TRUE),
    ('tana toraja', 'tana toraja', FALSE),
    ('tana toraja', 'kabupaten tana toraja', TRUE),
    ('tana toraja', 'kab tana toraja', TRUE),
    ('tana toraja', 'kota tana toraja', TRUE),
    ('toraja utara', 'toraja utara', FALSE),
    ('toraja utara', 'kabupaten toraja utara', TRUE),
    ('toraja utara', 'kab toraja utara', TRUE),
    ('toraja utara', 'kota toraja utara', TRUE),
    ('wajo', 'wajo', FALSE),
    ('wajo', 'kabupaten wajo', TRUE),
    ('wajo', 'kab wajo', TRUE),
    ('wajo', 'kota wajo', TRUE),
    ('makassar', 'makassar', FALSE),
    ('makassar', 'kabupaten makassar', TRUE),
    ('makassar', 'kab makassar', TRUE),
    ('makassar', 'kota makassar', TRUE),
    ('palopo', 'palopo', FALSE),
    ('palopo', 'kabupaten palopo', TRUE),
    ('palopo', 'kab palopo', TRUE),
    ('palopo', 'kota palopo', TRUE),
    ('parepare', 'parepare', FALSE),
    ('parepare', 'kabupaten parepare', TRUE),
    ('parepare', 'kab parepare', TRUE),
    ('parepare', 'kota parepare', TRUE),
    ('bombana', 'bombana', FALSE),
    ('bombana', 'kabupaten bombana', TRUE),
    ('bombana', 'kab bombana', TRUE),
    ('bombana', 'kota bombana', TRUE),
    ('buton', 'buton', FALSE),
    ('buton', 'kabupaten buton', TRUE),
    ('buton', 'kab buton', TRUE),
    ('buton', 'kota buton', TRUE),
    ('buton selatan', 'buton selatan', FALSE),
    ('buton selatan', 'kabupaten buton selatan', TRUE),
    ('buton selatan', 'kab buton selatan', TRUE),
    ('buton selatan', 'kota buton selatan', TRUE),
    ('buton tengah', 'buton tengah', FALSE),
    ('buton tengah', 'kabupaten buton tengah', TRUE),
    ('buton tengah', 'kab buton tengah', TRUE),
    ('buton tengah', 'kota buton tengah', TRUE),
    ('buton utara', 'buton utara', FALSE),
    ('buton utara', 'kabupaten buton utara', TRUE),
    ('buton utara', 'kab buton utara', TRUE),
    ('buton utara', 'kota buton utara', TRUE),
    ('kolaka', 'kolaka', FALSE),
    ('kolaka', 'kabupaten kolaka', TRUE),
    ('kolaka', 'kab kolaka', TRUE),
    ('kolaka', 'kota kolaka', TRUE),
    ('kolaka timur', 'kolaka timur', FALSE),
    ('kolaka timur', 'kabupaten kolaka timur', TRUE),
    ('kolaka timur', 'kab kolaka timur', TRUE),
    ('kolaka timur', 'kota kolaka timur', TRUE),
    ('kolaka utara', 'kolaka utara', FALSE),
    ('kolaka utara', 'kabupaten kolaka utara', TRUE),
    ('kolaka utara', 'kab kolaka utara', TRUE),
    ('kolaka utara', 'kota kolaka utara', TRUE),
    ('konawe', 'konawe', FALSE),
    ('konawe', 'kabupaten konawe', TRUE),
    ('konawe', 'kab konawe', TRUE),
    ('konawe', 'kota konawe', TRUE),
    ('konawe kepulauan', 'konawe kepulauan', FALSE),
    ('konawe kepulauan', 'kabupaten konawe kepulauan', TRUE),
    ('konawe kepulauan', 'kab konawe kepulauan', TRUE),
    ('konawe kepulauan', 'kota konawe kepulauan', TRUE),
    ('konawe selatan', 'konawe selatan', FALSE),
    ('konawe selatan', 'kabupaten konawe selatan', TRUE),
    ('konawe selatan', 'kab konawe selatan', TRUE),
    ('konawe selatan', 'kota konawe selatan', TRUE),
    ('konawe utara', 'konawe utara', FALSE),
    ('konawe utara', 'kabupaten konawe utara', TRUE),
    ('konawe utara', 'kab konawe utara', TRUE),
    ('konawe utara', 'kota konawe utara', TRUE),
    ('muna', 'muna', FALSE),
    ('muna', 'kabupaten muna', TRUE),
    ('muna', 'kab muna', TRUE),
    ('muna', 'kota muna', TRUE),
    ('muna barat', 'muna barat', FALSE),
    ('muna barat', 'kabupaten muna barat', TRUE),
    ('muna barat', 'kab muna barat', TRUE),
    ('muna barat', 'kota muna barat', TRUE),
    ('wakatobi', 'wakatobi', FALSE),
    ('wakatobi', 'kabupaten wakatobi', TRUE),
    ('wakatobi', 'kab wakatobi', TRUE),
    ('wakatobi', 'kota wakatobi', TRUE),
    ('kendari', 'kendari', FALSE),
    ('kendari', 'kabupaten kendari', TRUE),
    ('kendari', 'kab kendari', TRUE),
    ('kendari', 'kota kendari', TRUE),
    ('bau bau', 'bau bau', FALSE),
    ('bau bau', 'kabupaten bau bau', TRUE),
    ('bau bau', 'kab bau bau', TRUE),
    ('bau bau', 'kota bau bau', TRUE),
    ('mamasa', 'mamasa', FALSE),
    ('mamasa', 'kabupaten mamasa', TRUE),
    ('mamasa', 'kab mamasa', TRUE),
    ('mamasa', 'kota mamasa', TRUE),
    ('mamuju', 'mamuju', FALSE),
    ('mamuju', 'kabupaten mamuju', TRUE),
    ('mamuju', 'kab mamuju', TRUE),
    ('mamuju', 'kota mamuju', TRUE),
    ('mamuju tengah', 'mamuju tengah', FALSE),
    ('mamuju tengah', 'kabupaten mamuju tengah', TRUE),
    ('mamuju tengah', 'kab mamuju tengah', TRUE),
    ('mamuju tengah', 'kota mamuju tengah', TRUE),
    ('mamuju utara', 'mamuju utara', FALSE),
    ('mamuju utara', 'kabupaten mamuju utara', TRUE),
    ('mamuju utara', 'kab mamuju utara', TRUE),
    ('mamuju utara', 'kota mamuju utara', TRUE),
    ('pasangkayu', 'pasangkayu', FALSE),
    ('pasangkayu', 'kabupaten pasangkayu', TRUE),
    ('pasangkayu', 'kab pasangkayu', TRUE),
    ('pasangkayu', 'kota pasangkayu', TRUE),
    ('polewali mandar', 'polewali mandar', FALSE),
    ('polewali mandar', 'kabupaten polewali mandar', TRUE),
    ('polewali mandar', 'kab polewali mandar', TRUE),
    ('polewali mandar', 'kota polewali mandar', TRUE),
    ('boalemo', 'boalemo', FALSE),
    ('boalemo', 'kabupaten boalemo', TRUE),
    ('boalemo', 'kab boalemo', TRUE),
    ('boalemo', 'kota boalemo', TRUE),
    ('bone bolango', 'bone bolango', FALSE),
    ('bone bolango', 'kabupaten bone bolango', TRUE),
    ('bone bolango', 'kab bone bolango', TRUE),
    ('bone bolango', 'kota bone bolango', TRUE),
    ('gorontalo', 'gorontalo', FALSE),
    ('gorontalo', 'kabupaten gorontalo', TRUE),
    ('gorontalo', 'kab gorontalo', TRUE),
    ('gorontalo', 'kota gorontalo', TRUE),
    ('gorontalo utara', 'gorontalo utara', FALSE),
    ('gorontalo utara', 'kabupaten gorontalo utara', TRUE),
    ('gorontalo utara', 'kab gorontalo utara', TRUE),
    ('gorontalo utara', 'kota gorontalo utara', TRUE),
    ('pohuwato', 'pohuwato', FALSE),
    ('pohuwato', 'kabupaten pohuwato', TRUE),
    ('pohuwato', 'kab pohuwato', TRUE),
    ('pohuwato', 'kota pohuwato', TRUE),
    ('buru', 'buru', FALSE),
    ('buru', 'kabupaten buru', TRUE),
    ('buru', 'kab buru', TRUE),
    ('buru', 'kota buru', TRUE),
    ('buru selatan', 'buru selatan', FALSE),
    ('buru selatan', 'kabupaten buru selatan', TRUE),
    ('buru selatan', 'kab buru selatan', TRUE),
    ('buru selatan', 'kota buru selatan', TRUE),
    ('kepulauan aru', 'kepulauan aru', FALSE),
    ('kepulauan aru', 'kabupaten kepulauan aru', TRUE),
    ('kepulauan aru', 'kab kepulauan aru', TRUE),
    ('kepulauan aru', 'kota kepulauan aru', TRUE),
    ('kepulauan tanimbar', 'kepulauan tanimbar', FALSE),
    ('kepulauan tanimbar', 'kabupaten kepulauan tanimbar', TRUE),
    ('kepulauan tanimbar', 'kab kepulauan tanimbar', TRUE),
    ('kepulauan tanimbar', 'kota kepulauan tanimbar', TRUE),
    ('kepulauan yapen', 'kepulauan yapen', FALSE),
    ('kepulauan yapen', 'kabupaten kepulauan yapen', TRUE),
    ('kepulauan yapen', 'kab kepulauan yapen', TRUE),
    ('kepulauan yapen', 'kota kepulauan yapen', TRUE),
    ('maluku barat daya', 'maluku barat daya', FALSE),
    ('maluku barat daya', 'kabupaten maluku barat daya', TRUE),
    ('maluku barat daya', 'kab maluku barat daya', TRUE),
    ('maluku barat daya', 'kota maluku barat daya', TRUE),
    ('maluku tengah', 'maluku tengah', FALSE),
    ('maluku tengah', 'kabupaten maluku tengah', TRUE),
    ('maluku tengah', 'kab maluku tengah', TRUE),
    ('maluku tengah', 'kota maluku tengah', TRUE),
    ('maluku tenggara', 'maluku tenggara', FALSE),
    ('maluku tenggara', 'kabupaten maluku tenggara', TRUE),
    ('maluku tenggara', 'kab maluku tenggara', TRUE),
    ('maluku tenggara', 'kota maluku tenggara', TRUE),
    ('maluku tenggara barat', 'maluku tenggara barat', FALSE),
    ('maluku tenggara barat', 'kabupaten maluku tenggara barat', TRUE),
    ('maluku tenggara barat', 'kab maluku tenggara barat', TRUE),
    ('maluku tenggara barat', 'kota maluku tenggara barat', TRUE),
    ('seram bagian barat', 'seram bagian barat', FALSE),
    ('seram bagian barat', 'kabupaten seram bagian barat', TRUE),
    ('seram bagian barat', 'kab seram bagian barat', TRUE),
    ('seram bagian barat', 'kota seram bagian barat', TRUE),
    ('seram bagian timur', 'seram bagian timur', FALSE),
    ('seram bagian timur', 'kabupaten seram bagian timur', TRUE),
    ('seram bagian timur', 'kab seram bagian timur', TRUE),
    ('seram bagian timur', 'kota seram bagian timur', TRUE),
    ('ambon', 'ambon', FALSE),
    ('ambon', 'kabupaten ambon', TRUE),
    ('ambon', 'kab ambon', TRUE),
    ('ambon', 'kota ambon', TRUE),
    ('ternate', 'ternate', FALSE),
    ('ternate', 'kabupaten ternate', TRUE),
    ('ternate', 'kab ternate', TRUE),
    ('ternate', 'kota ternate', TRUE),
    ('tidore kepulauan', 'tidore kepulauan', FALSE),
    ('tidore kepulauan', 'kabupaten tidore kepulauan', TRUE),
    ('tidore kepulauan', 'kab tidore kepulauan', TRUE),
    ('tidore kepulauan', 'kota tidore kepulauan', TRUE),
    ('halmahera barat', 'halmahera barat', FALSE),
    ('halmahera barat', 'kabupaten halmahera barat', TRUE),
    ('halmahera barat', 'kab halmahera barat', TRUE),
    ('halmahera barat', 'kota halmahera barat', TRUE),
    ('halmahera selatan', 'halmahera selatan', FALSE),
    ('halmahera selatan', 'kabupaten halmahera selatan', TRUE),
    ('halmahera selatan', 'kab halmahera selatan', TRUE),
    ('halmahera selatan', 'kota halmahera selatan', TRUE),
    ('halmahera tengah', 'halmahera tengah', FALSE),
    ('halmahera tengah', 'kabupaten halmahera tengah', TRUE),
    ('halmahera tengah', 'kab halmahera tengah', TRUE),
    ('halmahera tengah', 'kota halmahera tengah', TRUE),
    ('halmahera timur', 'halmahera timur', FALSE),
    ('halmahera timur', 'kabupaten halmahera timur', TRUE),
    ('halmahera timur', 'kab halmahera timur', TRUE),
    ('halmahera timur', 'kota halmahera timur', TRUE),
    ('halmahera utara', 'halmahera utara', FALSE),
    ('halmahera utara', 'kabupaten halmahera utara', TRUE),
    ('halmahera utara', 'kab halmahera utara', TRUE),
    ('halmahera utara', 'kota halmahera utara', TRUE),
    ('kepulauan sula', 'kepulauan sula', FALSE),
    ('kepulauan sula', 'kabupaten kepulauan sula', TRUE),
    ('kepulauan sula', 'kab kepulauan sula', TRUE),
    ('kepulauan sula', 'kota kepulauan sula', TRUE),
    ('pulau morotai', 'pulau morotai', FALSE),
    ('pulau morotai', 'kabupaten pulau morotai', TRUE),
    ('pulau morotai', 'kab pulau morotai', TRUE),
    ('pulau morotai', 'kota pulau morotai', TRUE),
    ('pulau taliabu', 'pulau taliabu', FALSE),
    ('pulau taliabu', 'kabupaten pulau taliabu', TRUE),
    ('pulau taliabu', 'kab pulau taliabu', TRUE),
    ('pulau taliabu', 'kota pulau taliabu', TRUE),
    ('fak fak', 'fak fak', FALSE),
    ('fak fak', 'kabupaten fak fak', TRUE),
    ('fak fak', 'kab fak fak', TRUE),
    ('fak fak', 'kota fak fak', TRUE),
    ('kaimana', 'kaimana', FALSE),
    ('kaimana', 'kabupaten kaimana', TRUE),
    ('kaimana', 'kab kaimana', TRUE),
    ('kaimana', 'kota kaimana', TRUE),
    ('manokwari', 'manokwari', FALSE),
    ('manokwari', 'kabupaten manokwari', TRUE),
    ('manokwari', 'kab manokwari', TRUE),
    ('manokwari', 'kota manokwari', TRUE),
    ('manokwari selatan', 'manokwari selatan', FALSE),
    ('manokwari selatan', 'kabupaten manokwari selatan', TRUE),
    ('manokwari selatan', 'kab manokwari selatan', TRUE),
    ('manokwari selatan', 'kota manokwari selatan', TRUE),
    ('pegunungan arfak', 'pegunungan arfak', FALSE),
    ('pegunungan arfak', 'kabupaten pegunungan arfak', TRUE),
    ('pegunungan arfak', 'kab pegunungan arfak', TRUE),
    ('pegunungan arfak', 'kota pegunungan arfak', TRUE),
    ('sorong', 'sorong', FALSE),
    ('sorong', 'kabupaten sorong', TRUE),
    ('sorong', 'kab sorong', TRUE),
    ('sorong', 'kota sorong', TRUE),
    ('sorong selatan', 'sorong selatan', FALSE),
    ('sorong selatan', 'kabupaten sorong selatan', TRUE),
    ('sorong selatan', 'kab sorong selatan', TRUE),
    ('sorong selatan', 'kota sorong selatan', TRUE),
    ('tambrauw', 'tambrauw', FALSE),
    ('tambrauw', 'kabupaten tambrauw', TRUE),
    ('tambrauw', 'kab tambrauw', TRUE),
    ('tambrauw', 'kota tambrauw', TRUE),
    ('teluk bintuni', 'teluk bintuni', FALSE),
    ('teluk bintuni', 'kabupaten teluk bintuni', TRUE),
    ('teluk bintuni', 'kab teluk bintuni', TRUE),
    ('teluk bintuni', 'kota teluk bintuni', TRUE),
    ('teluk wondama', 'teluk wondama', FALSE),
    ('teluk wondama', 'kabupaten teluk wondama', TRUE),
    ('teluk wondama', 'kab teluk wondama', TRUE),
    ('teluk wondama', 'kota teluk wondama', TRUE),
    ('asmat', 'asmat', FALSE),
    ('asmat', 'kabupaten asmat', TRUE),
    ('asmat', 'kab asmat', TRUE),
    ('asmat', 'kota asmat', TRUE),
    ('biak numfor', 'biak numfor', FALSE),
    ('biak numfor', 'kabupaten biak numfor', TRUE),
    ('biak numfor', 'kab biak numfor', TRUE),
    ('biak numfor', 'kota biak numfor', TRUE),
    ('boven digoel', 'boven digoel', FALSE),
    ('boven digoel', 'kabupaten boven digoel', TRUE),
    ('boven digoel', 'kab boven digoel', TRUE),
    ('boven digoel', 'kota boven digoel', TRUE),
    ('deiyai', 'deiyai', FALSE),
    ('deiyai', 'kabupaten deiyai', TRUE),
    ('deiyai', 'kab deiyai', TRUE),
    ('deiyai', 'kota deiyai', TRUE),
    ('dogiyai', 'dogiyai', FALSE),
    ('dogiyai', 'kabupaten dogiyai', TRUE),
    ('dogiyai', 'kab dogiyai', TRUE),
    ('dogiyai', 'kota dogiyai', TRUE),
    ('intan jaya', 'intan jaya', FALSE),
    ('intan jaya', 'kabupaten intan jaya', TRUE),
    ('intan jaya', 'kab intan jaya', TRUE),
    ('intan jaya', 'kota intan jaya', TRUE),
    ('jayapura', 'jayapura', FALSE),
    ('jayapura', 'kabupaten jayapura', TRUE),
    ('jayapura', 'kab jayapura', TRUE),
    ('jayapura', 'kota jayapura', TRUE),
    ('jayawijaya', 'jayawijaya', FALSE),
    ('jayawijaya', 'kabupaten jayawijaya', TRUE),
    ('jayawijaya', 'kab jayawijaya', TRUE),
    ('jayawijaya', 'kota jayawijaya', TRUE),
    ('keerom', 'keerom', FALSE),
    ('keerom', 'kabupaten keerom', TRUE),
    ('keerom', 'kab keerom', TRUE),
    ('keerom', 'kota keerom', TRUE),
    ('lanny jaya', 'lanny jaya', FALSE),
    ('lanny jaya', 'kabupaten lanny jaya', TRUE),
    ('lanny jaya', 'kab lanny jaya', TRUE),
    ('lanny jaya', 'kota lanny jaya', TRUE),
    ('mamberamo raya', 'mamberamo raya', FALSE),
    ('mamberamo raya', 'kabupaten mamberamo raya', TRUE),
    ('mamberamo raya', 'kab mamberamo raya', TRUE),
    ('mamberamo raya', 'kota mamberamo raya', TRUE),
    ('mamberamo tengah', 'mamberamo tengah', FALSE),
    ('mamberamo tengah', 'kabupaten mamberamo tengah', TRUE),
    ('mamberamo tengah', 'kab mamberamo tengah', TRUE),
    ('mamberamo tengah', 'kota mamberamo tengah', TRUE),
    ('mappi', 'mappi', FALSE),
    ('mappi', 'kabupaten mappi', TRUE),
    ('mappi', 'kab mappi', TRUE),
    ('mappi', 'kota mappi', TRUE),
    ('merauke', 'merauke', FALSE),
    ('merauke', 'kabupaten merauke', TRUE),
    ('merauke', 'kab merauke', TRUE),
    ('merauke', 'kota merauke', TRUE),
    ('mimika', 'mimika', FALSE),
    ('mimika', 'kabupaten mimika', TRUE),
    ('mimika', 'kab mimika', TRUE),
    ('mimika', 'kota mimika', TRUE),
    ('nabire', 'nabire', FALSE),
    ('nabire', 'kabupaten nabire', TRUE),
    ('nabire', 'kab nabire', TRUE),
    ('nabire', 'kota nabire', TRUE),
    ('nduga', 'nduga', FALSE),
    ('nduga', 'kabupaten nduga', TRUE),
    ('nduga', 'kab nduga', TRUE),
    ('nduga', 'kota nduga', TRUE),
    ('pegunungan bintang', 'pegunungan bintang', FALSE),
    ('pegunungan bintang', 'kabupaten pegunungan bintang', TRUE),
    ('pegunungan bintang', 'kab pegunungan bintang', TRUE),
    ('pegunungan bintang', 'kota pegunungan bintang', TRUE),
    ('puncak', 'puncak', FALSE),
    ('puncak', 'kabupaten puncak', TRUE),
    ('puncak', 'kab puncak', TRUE),
    ('puncak', 'kota puncak', TRUE),
    ('puncak jaya', 'puncak jaya', FALSE),
    ('puncak jaya', 'kabupaten puncak jaya', TRUE),
    ('puncak jaya', 'kab puncak jaya', TRUE),
    ('puncak jaya', 'kota puncak jaya', TRUE),
    ('sarmi', 'sarmi', FALSE),
    ('sarmi', 'kabupaten sarmi', TRUE),
    ('sarmi', 'kab sarmi', TRUE),
    ('sarmi', 'kota sarmi', TRUE),
    ('supiori', 'supiori', FALSE),
    ('supiori', 'kabupaten supiori', TRUE),
    ('supiori', 'kab supiori', TRUE),
    ('supiori', 'kota supiori', TRUE),
    ('tolikara', 'tolikara', FALSE),
    ('tolikara', 'kabupaten tolikara', TRUE),
    ('tolikara', 'kab tolikara', TRUE),
    ('tolikara', 'kota tolikara', TRUE),
    ('waropen', 'waropen', FALSE),
    ('waropen', 'kabupaten waropen', TRUE),
    ('waropen', 'kab waropen', TRUE),
    ('waropen', 'kota waropen', TRUE),
    ('yahukimo', 'yahukimo', FALSE),
    ('yahukimo', 'kabupaten yahukimo', TRUE),
    ('yahukimo', 'kab yahukimo', TRUE),
    ('yahukimo', 'kota yahukimo', TRUE),
    ('yalimo', 'yalimo', FALSE),
    ('yalimo', 'kabupaten yalimo', TRUE),
    ('yalimo', 'kab yalimo', TRUE),
    ('yalimo', 'kota yalimo', TRUE);

-- Verifikasi hasil insert
SELECT 'Kota/Kabupaten yang ditambahkan:' as info;
SELECT kabupaten_kota_name, COUNT(*) as keyword_count 
FROM kabupaten_kota_keywords 
GROUP BY kabupaten_kota_name 
ORDER BY kabupaten_kota_name;
